import {useEffect,useRef,useState} from 'react';
import {api,date,errorText} from './api';
import {Modal,Field,Select,Busy} from './ui';
import {flushFields} from './fieldChanges';
import type {Article,Job} from './types';

const PROFILE:Record<string,string>={audience:'账号受众',direction:'内容方向',expression:'表达方式',avoid:'禁用事项'};
const METRICS:Record<string,string>={reads:'阅读',likes:'点赞',shares:'分享',saves:'收藏'};
const STATES:Record<string,string>={soft:'软参考',confirmed:'已确认',pending:'待确认',disabled:'已停用',revoked:'已撤销',draft:'草稿',final:'人工定稿',published:'已发表',trash:'回收站'};
const CATEGORIES:Record<string,string>={expression:'表达',structure:'结构',rhythm:'节奏'};
const STAGES:Record<string,string>={topic:'选题',outline:'大纲',write:'写作',revise:'修改选段',edit:'整体编辑'};
type HistoryRow={article_id:string;title:string;column:string;topic:string;angle:string;reader_question:string;takeaway:string;status:string;published_at?:string;revision:number;updated:string;needs_review:boolean};
type Account={revision:number;profile:Record<string,string>;rules:any[];examples:any[];metrics:any[];pairs:any[];trends:any[];jobs:Job[]};

export default function AccountPanel({article,onClose,refreshArticle}:{article:Article|null;onClose:()=>void;refreshArticle:()=>Promise<void>}){
 const [account,setAccount]=useState<Account|null>(null),[tab,setTab]=useState('profile'),[error,setError]=useState(''),[pending,setPending]=useState(false);
 const [history,setHistory]=useState<{items:HistoryRow[];total:number}>({items:[],total:0}),[page,setPage]=useState(1),[query,setQuery]=useState(''),[column,setColumn]=useState('');
 const [chosen,setChosen]=useState(article?.id||''),[useData,setUseData]=useState<any>({uses:[],pairs:[]}),[job,setJob]=useState<Job|null>(null),[editHistory,setEditHistory]=useState<HistoryRow|null>(null);
 const [example,setExample]=useState({title:'',column:article?.brief.column||'运动科学',text:'',url:''});
 const [userAuthored,setUserAuthored]=useState(false);
 const [metric,setMetric]=useState<Record<string,string>>({published_at:'',observed_at:'',reads:'',likes:'',shares:'',saves:''});
 const ref=useRef<Account|null>(null),actions=useRef<Promise<any>>(Promise.resolve()),queue=useRef<Promise<any>>(Promise.resolve());ref.current=account;
 const active=job?.status==='queued'||job?.status==='running';
 async function reload(){const value=await api<Account>('/account');ref.current=value;setAccount(value);setJob(value.jobs[0]||null)}
 async function rows(){setHistory(await api('/account/history?'+new URLSearchParams({page:String(page),query,column,page_size:'30'})))}
 async function uses(){if(chosen)setUseData(await api('/articles/'+chosen+'/account-uses'));else setUseData({uses:[],pairs:[]})}
 useEffect(()=>{void reload().catch(e=>setError(errorText(e)))},[]);
 useEffect(()=>{if(article?.id)setChosen(article.id)},[article?.id]);
 useEffect(()=>{void rows().catch(e=>setError(errorText(e)))},[page,query,column]);
 useEffect(()=>{void uses().catch(e=>setError(errorText(e)))},[chosen,account?.revision]);
 useEffect(()=>{if(!active||!job)return;const timer=setInterval(()=>{void api<Job>('/jobs/'+job.id).then(async j=>{setJob(j);if(!['queued','running'].includes(j.status)){await reload();await uses()}}).catch(e=>setError(errorText(e)))},800);return()=>clearInterval(timer)},[job?.id,active]);
 function act(fn:()=>Promise<void>){const task=actions.current.catch(()=>{}).then(async()=>{setPending(true);setError('');try{await fn()}catch(e){setError(errorText(e))}finally{setPending(false)}});actions.current=task;return task}
 function enqueue(fn:()=>Promise<void>){const task=queue.current.catch(()=>{}).then(fn);queue.current=task;return task}
 function updateProfile(key:string,text:string){return enqueue(async()=>{
  const current=ref.current!;await api<Account>('/account/profile','PATCH',{revision:current.revision,profile:{...current.profile,[key]:text}});await reload();
 })}
 function action(collection:string,id:string,action:string,patch?:any){return enqueue(async()=>{await api(`/account/${collection}/${id}`,'POST',{revision:ref.current!.revision,action,patch:typeof patch==='function'?patch():patch});await reload()})}
 async function start(value:Record<string,unknown>){await flushFields();setJob(await api('/account/jobs','POST',{...value,revision:ref.current!.revision}))}
 async function upload(file:File,kind:string){await flushFields();const body=new FormData();body.append('file',file);body.append('kind',kind);body.append('revision',String(ref.current!.revision));body.append('column',example.column);body.append('title',example.title);body.append('user_authored',String(userAuthored));setJob(await api('/account/import','POST',body))}
 const disabled=pending||active;
 const controls=(collection:string,item:any)=><div className="row wrap">
  {item.status!=='confirmed'&&<button className="button secondary" disabled={disabled} onClick={()=>act(()=>action(collection,item.id,'confirm'))}>确认{collection==='rules'?'固定此偏好':'使用此表达参考'}</button>}
  {item.status==='confirmed'&&item.scope!=='account'&&<button className="text-button" disabled={disabled} onClick={()=>act(()=>action(collection,item.id,'expand'))}>明确扩大到全账号</button>}
  {['disabled','revoked'].includes(item.status)?<button className="text-button" disabled={disabled} onClick={()=>act(()=>action(collection,item.id,'enable'))}>重新启用为{collection==='rules'?'软参考':'待确认'}</button>:<><button className="text-button" disabled={disabled} onClick={()=>act(()=>action(collection,item.id,'disable'))}>停用</button><button className="text-button" disabled={disabled} onClick={()=>act(()=>action(collection,item.id,'revoke'))}>撤销使用</button></>}
  <button className="text-button" disabled={disabled} onClick={()=>act(()=>action(collection,item.id,'delete'))}>删除</button>
 </div>;
 const picker=<Select label="关联文章" value={chosen} onChange={setChosen}><option value="">请选择文章</option>{chosen&&!history.items.some(x=>x.article_id===chosen)&&<option value={chosen}>{article?.title||'已选择文章'}</option>}{history.items.filter(x=>x.status!=='trash').map(x=><option key={x.article_id} value={x.article_id}>{x.title} · {x.column}</option>)}</Select>;
 return <Modal title="账号与学习" wide onClose={()=>void act(async()=>{await flushFields();await refreshArticle();onClose()})}><div className="account-panel">
  <p className="muted">单公众号；偏好默认只用于原栏目，本篇要求优先。这里的参考不会作为事实依据。</p>
  <nav className="account-tabs" aria-label="账号管理">{[['profile','账号定位'],['history','历史索引'],['rules','人工改稿学习'],['examples','范文'],['metrics','效果记录'],['uses','本篇使用记录']].map(([key,label])=><button className={'button '+(tab===key?'secondary':'ghost')} key={key} onClick={()=>act(async()=>{await flushFields();setTab(key)})}>{label}</button>)}</nav>
  {error&&<p className="notice amber" role="alert">{error}<button className="text-button" onClick={()=>act(reload)}>刷新账号记录</button></p>}
  {!account?<Busy/>:<>
   {job&&<div className="notice"><p>上次账号任务：{active?<Busy text={job.message}/>:job.message}</p>{active&&<button className="button secondary" onClick={()=>act(async()=>setJob(await api('/jobs/'+job.id+'/cancel','POST')))}>停止账号任务</button>}{job.partial&&!active&&job.status!=='completed'&&<details><summary>保留的分析结果</summary><pre className="editorial-text">{job.partial}</pre></details>}</div>}
   {tab==='profile'&&<>{Object.entries(PROFILE).map(([key,label])=><Field key={key} label={label} value={account.profile[key]} multiline onCommit={s=>updateProfile(key,s)}/>)}<p className="muted">文章任务书和本次补充要求优先于账号定位。账号模型、Key 和研究参数仍在原设置中。</p></>}
   {(tab==='history'||tab==='metrics'||tab==='rules')&&<div className="account-search"><label className="field"><span>搜索历史主题、角度或结论</span><input aria-label="搜索历史主题、角度或结论" value={query} onChange={e=>{setPage(1);setQuery(e.target.value)}}/></label><label className="field"><span>筛选栏目</span><input aria-label="筛选栏目" value={column} placeholder="全部栏目" onChange={e=>{setPage(1);setColumn(e.target.value)}}/></label><div className="row"><button className="text-button" disabled={page===1} onClick={()=>setPage(p=>p-1)}>上一页历史</button><span>{page} / {Math.max(1,Math.ceil(history.total/30))} · 共 {history.total} 篇</span><button className="text-button" disabled={page*30>=history.total} onClick={()=>setPage(p=>p+1)}>下一页历史</button></div></div>}
   {tab==='history'&&<><p>完整保留历史；近30天重点参考，近7天加强提醒。同主题的新证据、新角度仍可继续。</p>{history.items.map(row=><details className="service-card" key={row.article_id}><summary>{row.title} · {STATES[row.status]} · {row.column}</summary><p>主题：{row.topic}</p><p>角度：{row.angle||'待补充'}</p><p>读者问题：{row.reader_question||'待补充'}</p><p>结论：{row.takeaway||'待补充'}</p><p className="muted">{date(row.published_at||row.updated)} · {row.needs_review?'根据现有记录整理，待人工复核':'已人工维护'}</p><button className="text-button" disabled={row.status==='trash'} onClick={()=>setEditHistory(row)}>编辑索引</button></details>)}</>}
   {tab==='rules'&&<>{picker}<p>只学习明确的 AI 原稿／人工定稿差异。AI 自行编辑或仅点击定稿不算人工偏好。学习执行上游流程，模型调用会计费。</p>{useData.pairs.map((pair:any)=><div className="service-card" key={pair.id}><p>人工定稿 · {date(pair.created)} · {pair.column}</p><button className="button secondary" disabled={disabled||account.pairs.some(x=>x.id===pair.id)} onClick={()=>act(()=>start({kind:'learn',article_id:chosen,pair_id:pair.id}))}>{account.pairs.some(x=>x.id===pair.id)?'此改稿对已学习':'分析这一人工改稿对'}</button></div>)}{chosen&&!useData.pairs.length&&<p className="muted">这篇文章没有符合条件的人工改稿对。请从AI稿手动修改正文，再记录人工定稿。</p>}
    {account.rules.map(item=><div className="service-card" key={item.id}><p><strong>{CATEGORIES[item.category]}</strong> · {STATES[item.status]} · {item.scope==='account'?'全账号':item.column} · {item.sources.length} 个独立改稿对</p><Field label="偏好内容" value={item.text} multiline onCommit={text=>action('rules',item.id,'edit',{category:item.category,text})}/><p className="muted">置信度与重复次数按上游学习机制汇总；修改内容后重新作为本栏目软参考。</p><details><summary>学习来源与时间</summary>{item.sources.map((x:any)=><p key={x.id}>{x.title||'原文章记录'} · {date(x.created)} · AI原稿 → 人工定稿</p>)}</details>{controls('rules',item)}</div>)}
   </>}
   {tab==='examples'&&<><p>按上游方式提取真实表达片段，确认后每篇最多参考两份。保留所有权标记，人物、经历、事实不能挪作本篇依据。导入范文不调用模型。</p>{[['title','范文名称'],['column','范文栏目'],['url','范文网址（可选）'],['text','粘贴范文正文']].map(([key,label])=><label className="field" key={key}><span>{label}</span>{key==='text'?<textarea aria-label={label} rows={5} value={example.text} onChange={e=>setExample({...example,text:e.target.value})}/>:<input aria-label={label} value={example[key as keyof typeof example]} onChange={e=>setExample({...example,[key]:e.target.value})}/>}</label>)}<label className="check"><input type="checkbox" checked={userAuthored} onChange={e=>setUserAuthored(e.target.checked)}/>这是我本人创作的范文</label><div className="row wrap"><button className="button secondary" disabled={disabled||(!example.text&&!example.url)} onClick={()=>act(()=>start({kind:'example',...example,user_authored:userAuthored}))}>分析范文表达</button><label className="button secondary">导入范文文件<input type="file" accept=".txt,.md,.docx,.pdf" disabled={disabled} onChange={e=>{const f=e.target.files?.[0];if(f)void act(()=>upload(f,'example'));e.target.value=''}}/></label></div>
    {account.examples.map(item=><details className="service-card" key={item.id}><summary>{item.title} · {STATES[item.status]} · {item.scope==='account'?'全账号':item.column}</summary><p className="muted">来源：{item.source} · {date(item.created)} · {item.ownership==='user'?'本人作品':'第三方／未声明'}</p>{item.rules.map((rule:any,i:number)=><Field key={i} label={CATEGORIES[rule.category]+'参考 '+(i+1)} value={rule.text} multiline onCommit={text=>action('examples',item.id,'edit',()=>({rules:ref.current!.examples.find(x=>x.id===item.id).rules.map((r:any,j:number)=>j===i?{...r,text}:r)}))}/>)}{!item.rules.length&&<p>按原文的开头、转折和收尾提供表达参考。</p>}<details><summary>查看本地范文原文</summary><pre className="editorial-text">{item.text}</pre></details>{controls('examples',item)}</details>)}
   </>}
   {tab==='metrics'&&<>{picker}<p>日期按本地时间填写，使用相同观察窗口；未知指标留空。每项至少五篇独立文章才提供有限描述，不推因果。</p><div className="account-search">{[['published_at','发布时间'],['observed_at','统计时间'],...Object.entries(METRICS)].map(([key,label])=><label className="field" key={key}><span>{label}</span><input aria-label={label} type={key.endsWith('_at')?'datetime-local':'number'} min="0" value={metric[key]} onChange={e=>setMetric({...metric,[key]:e.target.value})}/></label>)}</div><button className="button secondary" disabled={disabled||!chosen||!metric.published_at||!metric.observed_at} onClick={()=>act(async()=>{await api('/account/metrics','POST',{revision:ref.current!.revision,rows:[{...metric,article_id:chosen,published_at:new Date(metric.published_at).toISOString(),observed_at:new Date(metric.observed_at).toISOString()}]});await reload()})}>保存效果记录</button>
    <details><summary>CSV批量导入格式</summary><p>UTF-8；时间可含时区，整批校验后保存。文章编号可从下方复制。</p><code>article_id,published_at,observed_at,reads,likes,shares,saves</code><p>当前文章编号：<code>{chosen||'请先选择文章'}</code></p></details><label className="button secondary">导入效果CSV<input type="file" accept=".csv" disabled={disabled} onChange={e=>{const f=e.target.files?.[0];if(f)void act(()=>upload(f,'metrics_csv'));e.target.value=''}}/></label>
    {account.trends.map((t,i)=><div className="service-card" key={i}><strong>{t.column} · {t.window_hours} 小时窗口 · {t.articles} 篇</strong><p>{t.note}</p>{Object.entries(t.metrics).map(([key,v]:[string,any])=><p key={key}>{METRICS[key]}：{v.n} 篇，均值 {v.mean}，范围 {v.minimum}—{v.maximum}</p>)}</div>)}
    {account.metrics.map(item=><details className="service-card" key={item.id}><summary>{item.title} · {item.window_hours} 小时 · {date(item.observed_at)}</summary><p>发布：{date(item.published_at)} · {item.column}</p><p>{Object.entries(METRICS).map(([key,label])=>label+'：'+(item[key]??'未知')).join('；')}</p><button className="text-button" disabled={disabled} onClick={()=>act(()=>action('metrics',item.id,'delete'))}>删除效果记录</button></details>)}
   </>}
   {tab==='uses'&&<>{picker}<p>以下是实际发给模型的参考，不能据此断言模型已经遵从。实际范文文件只用于表达参考。</p>{useData.uses.map((use:any)=><details className="service-card" key={use.id}><summary>{STAGES[use.stage]||use.stage} · {date(use.created)} · {use.status==='returned'?'已收到结果':use.status==='incomplete'?'请求未完成':'已开始请求'} · {use.revision===account.revision?'当前账号版本':'历史参考，账号已变更'}</summary><p>账号定位：{Object.entries(use.context.profile).map(([key,v])=>PROFILE[key]+'：'+(v||'未设置')).join('；')}</p><p>偏好 {use.context.rules.length} 条；范文表达 {use.context.examples.length} 份；历史 {use.context.history.length}/{use.context.history_total} 篇</p>{use.context.rules.map((r:any)=><p key={r.id}>{r.text} · {STATES[r.status]} · 权重 {r.weight} · {r.count} 对</p>)}{use.context.examples.map((e:any)=><p key={e.id}>{e.title}：{e.rules.map((r:any)=>r.text).join('；')}</p>)}<details><summary>实际提供的历史与效果</summary>{use.context.history.map((h:any)=><p key={h.article_id}>{h.title} · {h.recency} · {h.angle} · {h.reader_question} · {h.takeaway}</p>)}{use.context.trends.map((t:any,i:number)=><p key={i}>{t.column} · {t.window_hours}小时 · {t.articles}篇：{t.note}</p>)}</details></details>)}{!useData.uses.length&&<p className="muted">尚无本批功能接入后的调用记录。</p>}</>}
   <div className="row wrap account-footer"><button className="text-button" disabled={pending||account.revision===0} onClick={()=>act(async()=>{await flushFields();await api('/account/undo','POST',{revision:ref.current!.revision});await reload()})}>撤销上次账号修改</button><button className="text-button" disabled={pending} onClick={()=>act(reload)}>刷新账号记录</button><small>撤销立即影响后续调用。已携带旧参考的结果只保留待处理，文章历史恢复不会恢复账号偏好。</small></div>
  </>}
 </div>{editHistory&&<HistoryEditor row={editHistory} onClose={()=>setEditHistory(null)} onSaved={async()=>{setEditHistory(null);await rows();await refreshArticle()}}/>}</Modal>;
}

function HistoryEditor({row,onClose,onSaved}:{row:HistoryRow;onClose:()=>void;onSaved:()=>Promise<void>}){
 const [value,setValue]=useState({...row}),[error,setError]=useState(''),[saving,setSaving]=useState(false);
 async function save(){setSaving(true);try{const {topic,angle,reader_question,takeaway,status,published_at}=value;await api('/articles/'+row.article_id,'PATCH',{revision:row.revision,stage:'preferences',changes:{history_fields:{topic,angle,reader_question,takeaway,status,published_at:published_at||''}}});await onSaved()}catch(e){setError(errorText(e))}finally{setSaving(false)}}
 return <Modal title="编辑历史索引" onClose={onClose}><div className="account-panel">{[['topic','历史主题'],['angle','历史角度'],['reader_question','历史读者问题'],['takeaway','历史结论'],['published_at','发表时间（ISO日期）']].map(([key,label])=><label className="field" key={key}><span>{label}</span><input aria-label={label} value={String(value[key as keyof HistoryRow]||'')} onChange={e=>setValue({...value,[key]:e.target.value})}/></label>)}<Select label="文章状态" value={value.status} onChange={status=>setValue({...value,status})}>{['draft','final','published'].map(s=><option key={s} value={s}>{STATES[s]}</option>)}</Select>{error&&<p role="alert">{error}</p>}<button className="button primary" disabled={saving} onClick={()=>void save()}>保存历史索引</button></div></Modal>;
}
