import {useCallback,useEffect,useRef,useState,lazy,Suspense} from 'react';
import {Feather,Plus,ArrowUpRight,ArrowLeft,ArrowRight,Settings2,PanelRightClose,PanelRightOpen,BookOpen,Lightbulb,ListTree,PenLine,ShieldCheck,Image,Palette,Check,Clock3,FolderOpen,Upload,Sparkles,History,BarChart3,LoaderCircle,Square,SlidersHorizontal,ChevronRight,X,AlertCircle} from 'lucide-react';
import {api,date,errorText} from './api';
import {STAGES,LABELS,STATUS,type Article,type Settings as Config,type Meta,type Job,type Stage} from './types';
import {Modal,Field,Select,Toggle,Busy,Tag} from './ui';
import Settings from './Settings';
import BriefPanel from './BriefPanel';
const Editor=lazy(()=>import('./Editor'));
import {Topics,Sources,OutlinePanel,ReviewPanel,VisualPanel,LayoutPanel} from './Panels';

const ICONS={topic:Lightbulb,sources:BookOpen,outline:ListTree,write:PenLine,review:ShieldCheck,visual:Image,layout:Palette};
const DESCRIPTIONS:Record<string,string>={topic:'找到值得写，也值得读的角度。',sources:'把观点放在真实、可追溯的资料之上。',outline:'让每一节，都推进一个清晰的判断。',write:'专注表达，让文字靠近你的声音。',review:'对照证据，打磨观点与表达。',visual:'为文章选择有用、合适的图像。',layout:'预览阅读体验，带着完整作品离开。'};
const RUNLABEL:Record<string,string>={topic:'生成选题',sources:'分析选中素材',outline:'生成大纲',write:'生成初稿',review:'审核当前稿',visual:'生成配图方案',layout:'更新排版'};

export default function App(){
 const [list,setList]=useState<Article[]>([]),[article,setArticle]=useState<Article|null>(null),[meta,setMeta]=useState<Meta>({personas:[],themes:[]}),[cfg,setCfg]=useState<Config|null>(null);
 const [step,setStep]=useState<Stage>('topic'),[showSettings,setShowSettings]=useState(false),[newModal,setNewModal]=useState(false),[side,setSide]=useState(true),[sideTab,setSideTab]=useState('brief');
 const [sourceFocus,setSourceFocus]=useState(0);
 const [error,setError]=useState(''),[pending,setPending]=useState(0),[saved,setSaved]=useState(true),[job,setJob]=useState<Job|null>(null),[seconds,setSeconds]=useState(0),[records,setRecords]=useState<{type:string;rows:any[]}|null>(null);
 const [selected,setSelected]=useState(''),[instruction,setInstruction]=useState(''),[highlight,setHighlight]=useState(''),[newDomain,setNewDomain]=useState(''),[newTopic,setNewTopic]=useState(''),[newColumn,setNewColumn]=useState('运动科学');
 const articleRef=useRef<Article|null>(null);articleRef.current=article;
 const queue=useRef<Promise<any>>(Promise.resolve());const flush=useRef<()=>Promise<void>>(async()=>{});const mounted=useRef(true);const file=useRef<HTMLInputElement>(null);const pollLock=useRef(false);const pendingRef=useRef(0);const titleInput=useRef<HTMLInputElement>(null);
 const working=job?.status==='running'||job?.status==='queued';const busy=working||pending>0;
 useEffect(()=>{setSideTab(step==='review'?'review':step==='write'?'assist':'brief')},[step,article?.id]);
 function update(a:Article){articleRef.current=a;setArticle(a)}
 const report=(e:unknown)=>setError(errorText(e));
 async function act(fn:()=>Promise<void>){setPending(n=>n+1);pendingRef.current++;try{await fn()}catch(e){report(e)}finally{setPending(n=>n-1);pendingRef.current--}}
 async function refreshList(){setList(await api('/articles'))}
 async function open(id:string){await flush.current();await queue.current;await act(async()=>{const a=await api<Article>('/articles/'+id);update(a);setSourceFocus(0);setStep(STAGES.includes(a.current_stage as Stage)?a.current_stage as Stage:'topic');setSelected('');setInstruction('');setHighlight('');location.hash=id;const jobs=await api<Job[]>('/articles/'+id+'/jobs');setJob(jobs[0]||null);setSideTab('brief')})}
 useEffect(()=>{mounted.current=true;void act(async()=>{const [m,c,rows]=await Promise.all([api<Meta>('/meta'),api<Config>('/settings'),api<Article[]>('/articles')]);setMeta(m);setCfg(c);setList(rows);const id=location.hash.slice(1);if(id){const a=await api<Article>('/articles/'+id);update(a);setStep(STAGES.includes(a.current_stage as Stage)?a.current_stage as Stage:'topic');const jobs=await api<Job[]>('/articles/'+id+'/jobs');setJob(jobs[0]||null)}});return()=>{mounted.current=false}},[]);
 useEffect(()=>{const handler=(e:PromiseRejectionEvent)=>{e.preventDefault();report(e.reason)};window.addEventListener('unhandledrejection',handler);return()=>window.removeEventListener('unhandledrejection',handler)},[]);
 useEffect(()=>{if(!working||!job)return;const t=setInterval(()=>{setSeconds(Math.floor((Date.now()-Date.parse(job.created))/1000));if(pollLock.current||pendingRef.current)return;pollLock.current=true;void (async()=>{const j=await api<Job>('/jobs/'+job.id);if(!mounted.current)return;setJob(j);if(j.status!=='running'&&j.status!=='queued'){await queue.current;const a=await api<Article>('/articles/'+j.article_id);if(articleRef.current?.id===a.id){update(a);if((STAGES.includes(j.request.stage as Stage)||j.resumed_from)&&STAGES.includes(a.current_stage as Stage))setStep(a.current_stage as Stage);if(a.research?.pending||(j.request.stage==='research'&&!j.resumed_from))setStep('sources')}await refreshList();if(['failed','conflict','interrupted'].includes(j.status))setError(j.message)}})().catch(report).finally(()=>{pollLock.current=false})},800);return()=>clearInterval(t)},[job?.id,working]);
 const save=(changes:Partial<Article>,stage='preferences'):Promise<Article>=>{
   const id=articleRef.current!.id;setSaved(false);
   const current=queue.current.catch(()=>{}).then(async()=>{const a=articleRef.current;if(!a||a.id!==id)throw new Error('文章已切换，请重新操作');const next=await api<Article>('/articles/'+id,'PATCH',{revision:a.revision,stage,changes});update(next);setSaved(true);return next});
   queue.current=current;current.catch(report);return current;
 };
 async function run(stage:string,extra:Record<string,unknown>={}){await act(async()=>{await flush.current();await queue.current;const a=articleRef.current!;const j=await api<Job>('/articles/'+a.id+'/jobs','POST',{stage,revision:a.revision,chain:true,...extra});setJob(j);setSeconds(0);setError('')})}
 async function create(importFile?:File){await act(async()=>{let a=await api<Article>('/articles','POST',{column:newColumn,domain:newDomain,topic:newTopic});if(importFile){const body=new FormData();body.append('file',importFile);body.append('revision',String(a.revision));body.append('as_draft','true');a=await api<Article>('/articles/'+a.id+'/sources/file','POST',body)}update(a);setSourceFocus(0);setStep(importFile?'write':a.brief.topic?'sources':'topic');setJob(null);location.hash=a.id;setNewModal(false);setNewDomain('');setNewTopic('');await refreshList()})}
 const registerFlush=useCallback((fn:()=>Promise<void>)=>{flush.current=fn},[]);
 async function navigate(s:Stage){await act(async()=>{await flush.current();await queue.current;setStep(s);setHighlight('');setSelected('');if(s==='review')setSideTab('review');else if(s==='write')setSideTab('assist');else setSideTab('brief')})}
 async function home(){await act(async()=>{await flush.current();await queue.current;await refreshList();setArticle(null);setJob(null);flush.current=async()=>{};location.hash=''})}
 useEffect(()=>{const changed=()=>{const id=location.hash.slice(1);if(id&&id!==articleRef.current?.id)void open(id);else if(!id&&articleRef.current)void home()};window.addEventListener('hashchange',changed);return()=>window.removeEventListener('hashchange',changed)},[]);
 async function prepareExport(open=false){await flush.current();await queue.current;const a=articleRef.current!;return api(`/articles/${a.id}/exports${open?'/open':''}`,'POST',{revision:a.revision})}
 async function showRecords(type:string){await act(async()=>{await flush.current();await queue.current;setRecords({type,rows:await api('/articles/'+articleRef.current!.id+'/'+type)})})}
 const common=article?{onJob:setJob,a:article,save,act,update,run,busy}:null;
 const connected=!!cfg?.services.some(s=>s.key_set)&&!!cfg?.default_service;
 return <div className={'app '+(article?'in-article':'')}><header className="app-header"><button className="brand" onClick={()=>void home()}><span className="brand-icon"><Feather size={21}/></span><span>WeWrite<span className="brand-sub">创作工作台</span></span></button><div className="header-center">{article?<><span className="breadcrumb">文章库</span><ChevronRight size={14}/><span className="truncate">{article.title}</span></>:<span className="quiet-label">从灵感，到一篇好文章。</span>}</div><div className="header-actions"><span className="local-badge"><i/>本地运行</span><button className="button header-settings" onClick={()=>setShowSettings(true)}><Settings2 size={16}/><span>AI 服务与设置</span></button></div></header>
 {error&&<div className="toast" role="alert"><AlertCircle size={18}/><span>{error}</span><button aria-label="关闭提示" onClick={()=>setError('')}><X size={16}/></button></div>}
 {!article?<main className="home"><div className="home-top"><div className="home-intro"><span className="eyebrow"><span className="tiny-line"/> YOUR WRITING SPACE</span><h1>把值得分享的想法，<br/>写成<span>值得阅读的文章。</span></h1><p>选好一个角度，找到可靠的依据。<br/>让 AI 协作，让你的判断始终在场。</p><div className="row"><button className="button primary large" onClick={()=>setNewModal(true)}><Plus size={18}/>开始一篇新文章<ArrowUpRight size={17}/></button><button className="button secondary large" onClick={()=>file.current?.click()}><Upload size={17}/>导入已有稿件</button></div></div><div className="home-illustration" aria-hidden="true"><div className="paper shadow-paper"/><div className="paper main-paper"><div className="paper-kicker">A GOOD STORY STARTS HERE</div><Feather size={30}/><h3>好文章，<br/>有迹可循。</h3><div className="paper-lines"><i/><i/><i/></div><div className="paper-foot"><span>有依据的观点</span><span>清晰的表达</span></div></div><div className="float-note"><Check size={16}/>每一步，你都可以参与。</div><div className="paper-spark">✳</div></div></div>
 {!connected&&<div className="connect-banner"><div className="row"><span className="connect-icon"><SlidersHorizontal size={19}/></span><div><strong>先连接你习惯的 AI 服务</strong><p>填写 API Key，为选题、写作和审核分配不同模型。</p></div></div><button className="button secondary" onClick={()=>setShowSettings(true)}>配置 AI 服务<ArrowRight size={16}/></button></div>}
 <section className="library"><div className="row between"><div className="row"><h2>我的文章</h2><span className="count">{list.length}</span></div><span className="muted">自动保存在这台电脑上</span></div>{list.length?<div className="article-grid">{list.map(a=><button className="article-card" key={a.id} onClick={()=>void open(a.id)}><div className="row between"><Tag>{a.brief.column}</Tag><ArrowUpRight size={16}/></div><h3>{a.title}</h3><p>{a.brief.audience} · {a.brief.words} 字</p><div className="article-card-bottom"><span><i className="status-dot"/>{LABELS[a.current_stage]||'创作中'}</span><time>{date(a.updated)}</time></div></button>)}</div>:<div className="library-empty"><FolderOpen size={28}/><div><h3>这里，留给你的下一篇作品</h3><p>新建文章或导入旧稿，随时回来继续。</p></div></div>}</section><div className="home-process">{[['01','找到角度','把灵感变成具体问题'],['02','认真表达','资料、大纲与写作相连'],['03','打磨交付','审核、配图与排版就绪']].map(([n,t,d])=><div key={n}><span>{n}</span><div><strong>{t}</strong><p>{d}</p></div></div>)}</div><footer>WeWrite · 本地创作，按你的节奏。<span>基于 WeWrite 4.2.1</span></footer></main>:<div className="workspace"><aside className="flow-sidebar"><button className="back-link" onClick={()=>void home()}><ArrowLeft size={15}/>返回文章库</button><span className="eyebrow sidebar-caption">创作流程</span><nav>{STAGES.map((s,i)=>{const Icon=ICONS[s];return <button className={'stage-nav '+(step===s?'active ':'')+(article.workflow?.[s]?.allowed===false?'not-ready':'')} key={s} onClick={()=>void navigate(s)}><span className="stage-icon">{article.stages[s]==='done'?<Check size={16}/>:<Icon size={17}/>}</span><span className="grow"><strong>{LABELS[s]}</strong><small>{s==='visual'&&!article.visual.enabled?'按需添加':article.workflow?.[s]?.allowed===false?'待前置条件':STATUS[article.stages[s]]}</small></span><span className="stage-index">{String(i+1).padStart(2,'0')}</span></button>})}</nav><div className="flow-preferences"><div className="row between"><strong>执行节奏</strong><SlidersHorizontal size={14}/></div><div className="segmented"><button onClick={()=>void save({auto:Object.fromEntries(STAGES.map(s=>[s,false]))})}>全部手动</button><button onClick={()=>void save({auto:Object.fromEntries(STAGES.map(s=>[s,true]))})}>全部自动</button></div><p>每个环节也可独立设置</p></div><div className="sidebar-bottom"><button onClick={()=>void showRecords('versions')}><History size={16}/>历史版本</button><button onClick={()=>void showRecords('usage')}><BarChart3 size={16}/>调用与费用</button></div></aside>
 <main className={'article-main '+(side&&step!=='layout'?'has-side':'')}><div className="workspace-title"><div><div className="row"><span className="eyebrow">{String(STAGES.indexOf(step)+1).padStart(2,'0')} / 创作流程</span><Tag tone={article.stages[step]==='stale'?'amber':''}>{STATUS[article.stages[step]]}</Tag></div><h1>{LABELS[step]}</h1><p>{DESCRIPTIONS[step]}</p></div><div className="workspace-title-actions"><button className="icon-button" title={side?'收起侧栏':'展开侧栏'} onClick={()=>setSide(!side)}>{side?<PanelRightClose size={19}/>:<PanelRightOpen size={19}/>}</button>{step!=='sources'&&<button className="button primary" disabled={busy||article.workflow?.[step]?.allowed===false||(step==='visual'&&!article.visual.enabled)} onClick={()=>run(step)}>{working?<LoaderCircle size={16} className="spin"/>:<Sparkles size={16}/>} {RUNLABEL[step]}</button>}</div></div>
 <div className="stage-options"><Toggle small checked={article.auto[step]} label={article.auto[step]?'完成后自动继续':'完成后等我确认'} onChange={v=>void save({auto:{...article.auto,[step]:v}})}/><span className="save-state">{pending>0?<Busy text="处理中"/>:<><span className={'status-dot '+(!saved?'pending':'')}/>{saved?'修改自动保存':'正在保存…'}</>}</span></div>
 {article.workflow?.[step]?.allowed===false&&<div className="notice amber"><strong>{article.workflow[step].reason}</strong>{article.workflow[step].target!==step&&<button className="text-button" onClick={()=>navigate(article.workflow![step].target)}>前往{LABELS[article.workflow[step].target]}</button>}</div>}
 {job?.status==='needs_input'&&<div className="notice amber"><strong>{job.message}</strong>{article.research?.pending&&<button className="text-button" onClick={()=>{navigate('sources');setSourceFocus(Date.now())}}>处理核实问题</button>}</div>}
 {working&&job&&<div className="job-progress"><div className="row"><LoaderCircle size={17} className="spin"/><div><strong>{job.message}</strong><p>{LABELS[job.stage]||job.stage} · 已用 {seconds} 秒{job.partial?' · 已收到 '+job.partial.length+' 字符':''}</p></div></div><button className="button ghost" onClick={()=>act(async()=>{setJob(await api('/jobs/'+job.id+'/cancel','POST'));update(await api('/articles/'+article.id))})}><Square size={13}/>停止</button></div>}
 {job&&['failed','conflict','interrupted'].includes(job.status)&&<div className="notice amber"><strong>{job.message}</strong><div className="row"><button className="text-button" onClick={()=>run(job.request.stage,{...job.request,revision:article.revision,resume_job_id:''})}>从此环节重试</button>{job.partial&&<details><summary>查看已保留的生成结果</summary><pre className="partial-result">{job.partial}</pre></details>}</div></div>}
 {article.stages[step]==='stale'&&<div className="notice amber">前面的内容已改变，这份结果仍保留。请更新本环节，或编辑确认后继续。{step==='outline'&&!!article.outline.sections?.length&&<button className="button secondary" onClick={()=>act(async()=>update(await api('/articles/'+article.id+'/confirm/outline','POST',{revision:article.revision})))}>确认保留当前大纲</button>}</div>}
 <div className="stage-body">{step==='topic'&&<Topics {...common!}/>} {step==='sources'&&<Sources key={article.id} {...common!} focusToken={sourceFocus}/>} {step==='outline'&&<OutlinePanel {...common!}/>} {(step==='write'||step==='review')&&<><div className="article-title-edit"><Field label="文章标题" value={article.title} onCommit={v=>void save({title:v},'write')}/></div><Suspense fallback={<Busy text="正在打开编辑器"/>}><Editor key={article.id} sources={article.sources} onSourceSave={s=>save({sources:articleRef.current!.sources.map(x=>x.id===s.id?s:x)},'sources')} onLookup={async(sid,doi)=>{await flush.current();await queue.current;update(await api(`/articles/${article.id}/sources/${sid}/metadata`,'POST',{revision:articleRef.current!.revision,doi}))}} content={article.content} words={article.brief.words} onSave={s=>save({content:s},'write')} registerFlush={registerFlush} onSelection={s=>{setSelected(s);if(step==='write')setSideTab('assist')}} highlight={highlight}/></Suspense>{!side&&step==='review'&&<ReviewPanel a={article} act={act} update={update} locate={setHighlight}/>}</>}{step==='visual'&&<VisualPanel {...common!}/>} {step==='layout'&&<LayoutPanel a={article} save={save} act={act} run={run} busy={busy} meta={meta} prepareExport={prepareExport}/>}</div>
 <div className="stage-footer"><button className="button ghost" disabled={step==='topic'} onClick={()=>navigate(STAGES[STAGES.indexOf(step)-1])}><ArrowLeft size={15}/>上一步</button><span>{step==='layout'?'作品与所有修改，保存在本机。':'确认当前内容，按自己的节奏继续。'}</span>{step!=='layout'&&<button className="button secondary" onClick={()=>navigate(STAGES[STAGES.indexOf(step)+1])}>下一步 · {LABELS[STAGES[STAGES.indexOf(step)+1]]}<ArrowRight size={15}/></button>}</div></main>
 {side&&step!=='layout'&&<aside className="context-sidebar"><div className="context-tabs">{(step==='review'?[['review','审核意见'],['brief','写作设置']]:step==='write'?[['assist','AI 修改'],['brief','写作设置']]:[['brief','创作设置'],['sources','来源速览']]).map(([id,label])=><button key={id} className={sideTab===id?'active':''} onClick={()=>setSideTab(id)}>{label}</button>)}</div><div className="context-body">{sideTab==='brief'&&<BriefPanel a={article} meta={meta} save={save}/>} {sideTab==='review'&&<ReviewPanel a={article} act={act} update={update} locate={setHighlight}/>} {sideTab==='assist'&&<><div className="assistant-intro"><Sparkles size={23}/><h3>让这一段，更进一步</h3><p>选中正文，告诉 AI 如何调整。先看对比，再应用修改。</p></div><label className="field"><span>已选中的内容</span><textarea value={selected} onChange={e=>setSelected(e.target.value)} placeholder="在左侧正文中选择一段文字…" rows={5}/></label><div className="quick-prompts">{['更简洁','展开解释','更自然','补充适用条件'].map(t=><button key={t} onClick={()=>setInstruction(t)}>{t}</button>)}</div><label className="field"><span>这次如何修改</span><textarea value={instruction} onChange={e=>setInstruction(e.target.value)} placeholder="例如：保留事实，把这段写得更容易理解" rows={3}/></label><button className="button primary full" disabled={busy||!selected.trim()} onClick={()=>run('revise',{selected_text:selected,instruction,chain:false})}><Sparkles size={15}/>生成修改建议</button>{article.suggestions.map(s=><div className="suggestion" key={s.id}><strong>修改建议</strong><p>{s.explanation}</p><details><summary>修改前</summary><blockquote>{s.original}</blockquote></details><Field label="修改后（可以继续编辑）" multiline value={s.replacement} onCommit={v=>{s.replacement=v}}/><div className="row"><button className="button secondary" onClick={()=>act(async()=>{await flush.current();await queue.current;update(await api(`/articles/${article.id}/suggestions/${s.id}`,'POST',{revision:articleRef.current!.revision,action:'accept',replacement:s.replacement}))})}><Check size={14}/>应用</button><button className="text-button" onClick={()=>act(async()=>update(await api(`/articles/${article.id}/suggestions/${s.id}`,'POST',{revision:article.revision,action:'reject'})))}>放弃</button></div></div>)}</>}{sideTab==='sources'&&<><h3>文章的依据</h3>{article.sources.length?article.sources.filter(s=>s.selected).map(s=><div className="source-peek" key={s.id}><small>{s.id}</small><strong>{s.title}</strong><p>{s.summary}</p>{s.url&&<a className="text-link" href={s.url} target="_blank" rel="noreferrer">查看原文<ArrowUpRight size={13}/></a>}</div>):<p className="muted">还没有资料。到“素材”环节上传或搜索，来源会保存在这里。</p>}</>}</div></aside>}</div>}
 <input ref={file} hidden type="file" accept=".md,.txt,.docx,.pdf" onChange={e=>{if(e.target.files?.[0])void create(e.target.files[0]);e.target.value=''}}/>
 {showSettings&&cfg&&<Settings initial={cfg} onClose={()=>setShowSettings(false)} onSaved={setCfg}/>}
 {newModal&&<Modal title="开始一篇新文章" onClose={()=>setNewModal(false)}><p className="modal-intro">先给创作一个方向，其他细节可以边写边调整。</p><Select label="常用栏目" value={newColumn} onChange={setNewColumn}><option>运动科学</option><option>运动健康</option><option>AI</option></Select><Field label="想探索的领域" value={newDomain} onCommit={setNewDomain} placeholder="可留空，例如：青少年训练、AI 智能体"/><Field label="指定主题" value={newTopic} onCommit={setNewTopic} placeholder="可留空，让 AI 提供候选选题"/><div className="modal-footer"><span className="muted">默认逐步确认 · 不自动生图</span><button className="button primary" disabled={pending>0} onClick={()=>create()}><Plus size={16}/>创建文章</button></div></Modal>}
 {records&&<Modal title={records.type==='versions'?'历史版本':'调用与费用'} onClose={()=>setRecords(null)} wide>{!records.rows.length?<p className="muted">还没有记录。</p>:records.type==='versions'?records.rows.map(v=><div className="record-row" key={v.id}><div><strong>{v.label}</strong><p className="muted">{date(v.created)}</p></div><button className="button secondary" onClick={()=>act(async()=>{update(await api('/articles/'+article!.id+'/restore','POST',{version:v.id,revision:article!.revision}));setRecords(null)})}>恢复此版本</button></div>):<><p className="muted">金额为预估；未返回用量或没有价格时显示未知。图片预留包含可能已计费但未收到结果的请求。</p><div className="usage-table"><table><thead><tr><th>环节 / 模型</th><th>输入 / 输出</th><th>预估金额</th><th>时间</th></tr></thead><tbody>{records.rows.map(u=><tr key={u.id}><td>{LABELS[u.stage]||u.stage}<small>{u.model}</small></td><td>{u.input_tokens??'—'} / {u.output_tokens??'—'}</td><td>{u.estimated_cost==null?'未知':u.estimated_cost.toFixed(4)+' '+u.currency}{u.status==='reserved'&&<small>预算预留</small>}{u.status==='unknown'&&<small>结果未知，可能计费</small>}</td><td>{date(u.at)}</td></tr>)}</tbody></table></div></>}</Modal>}
 </div>
}
