import NativeTrace from './NativeTrace';
import ExtensionsPanel from './ExtensionsPanel';
import AccountPanel from './AccountPanel';
import EditorialPanel,{SynthesisSummary} from './EditorialPanel';
import {Pager} from './MaterialList';
import ArticleLibrary from './ArticleLibrary';
import {useCallback,useEffect,useRef,useState,lazy,Suspense} from 'react';
import {Feather,Plus,ArrowUpRight,ArrowLeft,ArrowRight,Settings2,PanelRightClose,PanelRightOpen,BookOpen,Lightbulb,ListTree,PenLine,ShieldCheck,Image,Palette,Check,Clock3,FolderOpen,Upload,Sparkles,History,BarChart3,LoaderCircle,Square,SlidersHorizontal,ChevronRight,X,AlertCircle} from 'lucide-react';
import {api,date,errorText} from './api';
import {STAGES,LABELS,STATUS,type Article,type Settings as Config,type Meta,type Job,type Stage,type Save} from './types';
import {Modal,Field,Select,Toggle,Busy,Tag} from './ui';
import Settings from './Settings';
import BriefPanel from './BriefPanel';
import ContextSidebar,{useSidebarState} from './ContextSidebar';
import StageContext,{type ContextSelection,type FocusTarget,type IssueFocus} from './StageContext';
import ReferenceDetails from './ReferenceDetails';
import {flushFields,hasDirtyFields,watchFields} from './fieldChanges';
import VersionNotice from './VersionNotice';
const Editor=lazy(()=>import('./Editor'));
import {Topics,Sources,OutlinePanel,ReviewPanel,VisualPanel,LayoutPanel} from './Panels';

const ICONS={topic:Lightbulb,sources:BookOpen,outline:ListTree,write:PenLine,review:ShieldCheck,visual:Image,layout:Palette};
const DESCRIPTIONS:Record<string,string>={topic:'找到值得写，也值得读的角度。',sources:'把观点放在真实、可追溯的资料之上。',outline:'让每一节，都推进一个清晰的判断。',write:'专注表达，让文字靠近你的声音。',review:'对照证据，打磨观点与表达。',visual:'为文章选择有用、合适的图像。',layout:'预览阅读体验，带着完整作品离开。'};
const RUNLABEL:Record<string,string>={topic:'生成选题',sources:'分析选中素材',outline:'生成大纲',write:'生成初稿',review:'审核当前稿',visual:'生成配图方案',layout:'更新排版'};

export default function App(){
 const [list,setList]=useState<Article[]>([]),[article,setArticle]=useState<Article|null>(null),[meta,setMeta]=useState<Meta>({personas:[],themes:[]}),[cfg,setCfg]=useState<Config|null>(null);
 const [step,setStep]=useState<Stage>('topic'),[showExtensions,setShowExtensions]=useState(false),[showAccount,setShowAccount]=useState(false),[showSettings,setShowSettings]=useState(false),[newModal,setNewModal]=useState(false);
 const [sourceFocus,setSourceFocus]=useState<IssueFocus>({token:0});
 const [contextSelection,setContextSelection]=useState<ContextSelection>(null),[inspectSource,setInspectSource]=useState('');
 const {side,tab:sideTab,narrow,change:changeSide}=useSidebarState(article?.id,step);
 const [error,setError]=useState(''),[pending,setPending]=useState(0),[saved,setSaved]=useState(true),[job,setJob]=useState<Job|null>(null),[seconds,setSeconds]=useState(0),[records,setRecords]=useState<{type:string;rows:any[];page?:number;total?:number}|null>(null);
 const [selected,setSelected]=useState(''),[instruction,setInstruction]=useState(''),[highlight,setHighlight]=useState(''),[newDomain,setNewDomain]=useState(''),[newTopic,setNewTopic]=useState(''),[newColumn,setNewColumn]=useState('运动科学');
 const articleRef=useRef<Article|null>(null);articleRef.current=article;
 const queue=useRef<Promise<any>>(Promise.resolve());const flush=useRef<()=>Promise<void>>(async()=>{});const mounted=useRef(true);const file=useRef<HTMLInputElement>(null);const pollLock=useRef(false);const pendingRef=useRef(0);const titleInput=useRef<HTMLInputElement>(null);
 const working=job?.status==='running'||job?.status==='queued';const busy=working||pending>0;
 useEffect(()=>{setContextSelection(null);setInspectSource('')},[article?.id]);
 useEffect(()=>{if(contextSelection&&article){const exists=contextSelection.kind==='source'?article.sources.some(s=>s.id===contextSelection.id):article.outline.sections?.some(s=>s.id===contextSelection.id);if(!exists)setContextSelection(null)}},[article,contextSelection]);
 async function flushChanges(){await flushFields();await flush.current();await queue.current}
 const transitions=useRef<Promise<void>>(Promise.resolve());
 function transition(change:()=>void){const id=articleRef.current?.id;const task=transitions.current.catch(()=>{}).then(async()=>{if(articleRef.current?.id!==id)return;await flushChanges();change()});transitions.current=task;return act(()=>task)}
 function changeSidebar(patch:{tab?:'context'|'brief';open?:boolean}){void transition(()=>changeSide(patch))}
 function selectContext(selection:ContextSelection,explicit=false){if(explicit)void transition(()=>{setContextSelection(selection);changeSide({tab:'context',open:true})});else setContextSelection(selection)}
 function locateContext(target:FocusTarget){void transition(()=>{if(target.kind==='section')setContextSelection({kind:'section',id:target.id});if(narrow)changeSide({open:false});requestAnimationFrame(()=>{const el=document.querySelector<HTMLElement>('[data-context-kind="'+target.kind+'"][data-context-id="'+CSS.escape(target.id)+'"]');el?.scrollIntoView({block:'center',behavior:'smooth'});el?.focus({preventScroll:true})})})}
 function locateIssue(id?:string){void transition(()=>{setStep('sources');setSourceFocus({token:Date.now(),id});if(narrow)changeSide({open:false})})}
 function update(a:Article){articleRef.current=a;setArticle(a)}
 const report=(e:unknown)=>setError(errorText(e));
 async function act(fn:()=>Promise<void>){setPending(n=>n+1);pendingRef.current++;try{await fn()}catch(e){report(e)}finally{setPending(n=>n-1);pendingRef.current--}}
 async function refreshVersion(){await act(async()=>{await flushChanges();const url=new URL(location.href);url.searchParams.set('opened',String(Date.now()));window.location.replace(url.href)})}
 async function refreshList(){setList((await api<{items:Article[]}>('/articles?page=1&page_size=20')).items)}
 async function open(id:string){await flushChanges();await act(async()=>{const a=await api<Article>('/articles/'+id);update(a);setSourceFocus({token:0});setStep(STAGES.includes(a.current_stage as Stage)?a.current_stage as Stage:'topic');setSelected('');setInstruction('');setHighlight('');location.hash=id;const jobs=await api<Job[]>('/articles/'+id+'/jobs');setJob(jobs[0]||null)})}
 useEffect(()=>{mounted.current=true;void act(async()=>{const [m,c,rows]=await Promise.all([api<Meta>('/meta'),api<Config>('/settings'),api<{items:Article[]}>('/articles?page=1&page_size=20')]);setMeta(m);setCfg(c);setList(rows.items);const id=location.hash.slice(1);if(id){const a=await api<Article>('/articles/'+id);update(a);setStep(STAGES.includes(a.current_stage as Stage)?a.current_stage as Stage:'topic');const jobs=await api<Job[]>('/articles/'+id+'/jobs');setJob(jobs[0]||null)}});return()=>{mounted.current=false}},[]);
 useEffect(()=>{const handler=(e:PromiseRejectionEvent)=>{e.preventDefault();report(e.reason)};window.addEventListener('unhandledrejection',handler);return()=>window.removeEventListener('unhandledrejection',handler)},[]);
 useEffect(()=>{if(!working||!job)return;const t=setInterval(()=>{setSeconds(Math.floor((Date.now()-Date.parse(job.created))/1000));if(pollLock.current||pendingRef.current)return;pollLock.current=true;void (async()=>{const j=await api<Job>('/jobs/'+job.id);if(!mounted.current)return;setJob(j);if(j.status!=='running'&&j.status!=='queued'){await flushChanges();const a=await api<Article>('/articles/'+j.article_id);if(articleRef.current?.id===a.id){update(a);if((STAGES.includes(j.request.stage as Stage)||j.resumed_from)&&STAGES.includes(a.current_stage as Stage))setStep(a.current_stage as Stage);if(j.request.stage==='research'&&!j.resumed_from)setStep('sources')}await refreshList();if(j.stage!=='source_import'&&['failed','conflict','interrupted'].includes(j.status))setError(j.message)}})().catch(report).finally(()=>{pollLock.current=false})},800);return()=>clearInterval(t)},[job?.id,working]);
 const saves=useRef(0),failedKeys=useRef(new Set<string>());
 useEffect(()=>watchFields(()=>setSaved(saves.current===0&&!failedKeys.current.size&&!hasDirtyFields())),[]);
 const save:Save=(changes,stage='preferences')=>{
   const id=articleRef.current!.id;saves.current++;setSaved(false);let keys:string[]=[];
   const current=queue.current.catch(()=>{}).then(async()=>{const a=articleRef.current;if(!a||a.id!==id)throw new Error('文章已切换，请重新操作');const patch=typeof changes==='function'?changes(a):changes;keys=Object.keys(patch).map(k=>id+':'+k);const next=await api<Article>('/articles/'+id,'PATCH',{revision:a.revision,stage,changes:patch});keys.forEach(k=>failedKeys.current.delete(k));update(next);return next});
   const tracked=current.catch(e=>{keys.forEach(k=>failedKeys.current.add(k));throw e}).finally(()=>{saves.current--;setSaved(saves.current===0&&!failedKeys.current.size&&!hasDirtyFields())});queue.current=tracked;tracked.catch(report);return tracked;
 };
 async function run(stage:string,extra:Record<string,unknown>={}){await act(async()=>{await flushChanges();const a=articleRef.current!;const j=await api<Job>('/articles/'+a.id+'/jobs','POST',{stage,revision:a.revision,chain:true,...extra});setJob(j);setSeconds(0);setError('')})}
 const reviewLock=useRef(false);
 async function reviewDecision(id:string,action:'accept'|'reject',replacement?:string){
  if(reviewLock.current)return;reviewLock.current=true;
  try{await act(async()=>{
   const articleId=articleRef.current!.id;const round=articleRef.current!.review.round_id;
   await flushChanges();
   const a=articleRef.current!;if(a.id!==articleId||a.review.round_id!==round)throw new Error('文章或审核已更新，请查看当前意见');
   const next=await api<Article>(`/articles/${a.id}/review/${id}`,'POST',{revision:a.revision,action,replacement});
   if(articleRef.current?.id!==a.id)return;update(next);
   const jobs=await api<Job[]>('/articles/'+a.id+'/jobs');if(articleRef.current?.id===a.id)setJob(jobs[0]||null);
  })}finally{reviewLock.current=false}
 }
 async function create(importFile?:File){await act(async()=>{let a=await api<Article>('/articles','POST',{column:newColumn,domain:newDomain,topic:newTopic});if(importFile){const body=new FormData();body.append('file',importFile);body.append('revision',String(a.revision));body.append('as_draft','true');a=await api<Article>('/articles/'+a.id+'/sources/file','POST',body)}update(a);setSourceFocus({token:0});setStep(importFile?'write':a.brief.topic?'sources':'topic');setJob(null);location.hash=a.id;setNewModal(false);setNewDomain('');setNewTopic('');await refreshList()})}
 const registerFlush=useCallback((fn:()=>Promise<void>)=>{flush.current=fn},[]);
 async function navigate(s:Stage){await transition(()=>{setStep(s);setHighlight('');setSelected('')})}
 async function home(){await act(async()=>{await flushChanges();await refreshList();setArticle(null);setJob(null);flush.current=async()=>{};location.hash=''})}
 useEffect(()=>{const changed=()=>{const id=location.hash.slice(1);if(id&&id!==articleRef.current?.id)void open(id);else if(!id&&articleRef.current)void home()};window.addEventListener('hashchange',changed);return()=>window.removeEventListener('hashchange',changed)},[]);
 async function prepareExport(open=false){await flushChanges();const a=articleRef.current!;return api(`/articles/${a.id}/exports${open?'/open':''}`,'POST',{revision:a.revision})}
 async function showRecords(type:string,page=1){await act(async()=>{await flushChanges();const result=await api('/articles/'+articleRef.current!.id+'/'+type+(type==='versions'?'?page='+page+'&page_size=50':''));setRecords(type==='versions'?{type,rows:result.items,page,total:result.total}:{type,rows:result})})}
 const common=article?{onJob:(j:Job)=>{setJob(j);if(['queued','running'].includes(j.status))setError('')},a:article,save,act,update,run,busy,prepare:async()=>{await flushChanges();return articleRef.current!},navigate}:null;
 const connected=!!cfg?.services.some(s=>s.key_set)&&!!cfg?.default_service;
 return <div className={'app '+(article?'in-article':'')}><header className="app-header"><button className="brand" onClick={()=>void home()}><span className="brand-icon"><Feather size={21}/></span><span>WeWrite<span className="brand-sub">创作工作台</span></span></button><div className="header-center">{article?<><span className="breadcrumb">文章库</span><ChevronRight size={14}/><span className="truncate">{article.title}</span></>:<span className="quiet-label">从灵感，到一篇好文章。</span>}</div><div className="header-actions"><span className="local-badge"><i/>本地运行 · v{__APP_VERSION__}</span><button className="button" onClick={()=>void transition(()=>setShowAccount(true))}>账号与学习</button><button className="button" onClick={()=>void transition(()=>setShowExtensions(true))}>扩展</button><button className="button header-settings" onClick={()=>setShowSettings(true)}><Settings2 size={16}/><span>AI 服务与设置</span></button></div></header>
 {showExtensions&&<ExtensionsPanel article={article} prepare={async()=>{await flushChanges();return articleRef.current}} refresh={async()=>{setMeta(await api('/meta'));if(articleRef.current)update(await api('/articles/'+articleRef.current.id));await refreshList()}} onClose={()=>setShowExtensions(false)}/>}
 {showAccount&&<AccountPanel article={article} onClose={()=>setShowAccount(false)} refreshArticle={async()=>{if(articleRef.current)update(await api('/articles/'+articleRef.current.id));await refreshList()}}/>}
 <VersionNotice busy={busy} onRefresh={refreshVersion}/>
 {error&&<div className="toast" role="alert"><AlertCircle size={18}/><span>{error}</span><button aria-label="关闭提示" onClick={()=>setError('')}><X size={16}/></button></div>}
 {!article?<main className="home"><div className="home-top"><div className="home-intro"><span className="eyebrow"><span className="tiny-line"/> YOUR WRITING SPACE</span><h1>把值得分享的想法，<br/>写成<span>值得阅读的文章。</span></h1><p>选好一个角度，找到可靠的依据。<br/>让 AI 协作，让你的判断始终在场。</p><div className="row"><button className="button primary large" onClick={()=>setNewModal(true)}><Plus size={18}/>开始一篇新文章<ArrowUpRight size={17}/></button><button className="button secondary large" onClick={()=>file.current?.click()}><Upload size={17}/>导入已有稿件</button></div></div><div className="home-illustration" aria-hidden="true"><div className="paper shadow-paper"/><div className="paper main-paper"><div className="paper-kicker">A GOOD STORY STARTS HERE</div><Feather size={30}/><h3>好文章，<br/>有迹可循。</h3><div className="paper-lines"><i/><i/><i/></div><div className="paper-foot"><span>有依据的观点</span><span>清晰的表达</span></div></div><div className="float-note"><Check size={16}/>每一步，你都可以参与。</div><div className="paper-spark">✳</div></div></div>
 {!connected&&<div className="connect-banner"><div className="row"><span className="connect-icon"><SlidersHorizontal size={19}/></span><div><strong>先连接你习惯的 AI 服务</strong><p>填写 API Key，为选题、写作和审核分配不同模型。</p></div></div><button className="button secondary" onClick={()=>setShowSettings(true)}>配置 AI 服务<ArrowRight size={16}/></button></div>}
 <ArticleLibrary articles={list} onOpen={id=>void open(id)} onChanged={refreshList}/><div className="home-process">{[['01','找到角度','把灵感变成具体问题'],['02','认真表达','资料、大纲与写作相连'],['03','打磨交付','审核、配图与排版就绪']].map(([n,t,d])=><div key={n}><span>{n}</span><div><strong>{t}</strong><p>{d}</p></div></div>)}</div><footer>WeWrite · 本地创作，按你的节奏。<span>基于 WeWrite 4.2.1</span></footer></main>:<div className="workspace"><aside className="flow-sidebar"><button className="back-link" onClick={()=>void home()}><ArrowLeft size={15}/>返回文章库</button><span className="eyebrow sidebar-caption">创作流程</span><nav>{STAGES.map((s,i)=>{const Icon=ICONS[s];return <button className={'stage-nav '+(step===s?'active ':'')+(article.workflow?.[s]?.allowed===false?'not-ready':'')} key={s} onClick={()=>void navigate(s)}><span className="stage-icon">{article.stages[s]==='done'?<Check size={16}/>:<Icon size={17}/>}</span><span className="grow"><strong>{LABELS[s]}</strong><small>{s==='visual'&&!article.visual.enabled?'按需添加':article.workflow?.[s]?.allowed===false?'待前置条件':STATUS[article.stages[s]]}</small></span><span className="stage-index">{String(i+1).padStart(2,'0')}</span></button>})}</nav><div className="flow-preferences"><div className="row between"><strong>执行节奏</strong><SlidersHorizontal size={14}/></div><div className="segmented"><button onClick={()=>void save({auto:Object.fromEntries(STAGES.map(s=>[s,false]))})}>全部手动</button><button onClick={()=>void save({auto:Object.fromEntries(STAGES.map(s=>[s,true]))})}>全部自动</button></div><p>每个环节也可独立设置</p></div><div className="sidebar-bottom"><button onClick={()=>void showRecords('versions')}><History size={16}/>历史版本</button><button onClick={()=>void showRecords('usage')}><BarChart3 size={16}/>调用记录</button></div></aside>
 <main className={'article-main '+(side&&step!=='layout'?'has-side':'')}><div className="workspace-title"><div><div className="row"><span className="eyebrow">{String(STAGES.indexOf(step)+1).padStart(2,'0')} / 创作流程</span><Tag tone={article.stages[step]==='stale'?'amber':''}>{STATUS[article.stages[step]]}</Tag></div><h1>{LABELS[step]}</h1><p>{DESCRIPTIONS[step]}</p></div><div className="workspace-title-actions">{step!=='layout'&&<button className="icon-button" title={side?'收起侧栏':'展开侧栏'} aria-label={side?'收起侧栏':'展开侧栏'} aria-expanded={side} aria-controls="context-sidebar" onClick={()=>changeSidebar({open:!side})}>{side?<PanelRightClose size={19}/>:<PanelRightOpen size={19}/>}</button>}{step!=='sources'&&<button className="button primary" disabled={busy||article.workflow?.[step]?.allowed===false||(step==='visual'&&!article.visual.enabled)} onClick={()=>run(step)}>{working?<LoaderCircle size={16} className="spin"/>:<Sparkles size={16}/>} {RUNLABEL[step]}</button>}</div></div>
 <div className="stage-options"><Toggle small checked={article.auto[step]} label={article.auto[step]?'完成后自动继续':'完成后等我确认'} onChange={v=>save(current=>({auto:{...current.auto,[step]:v}}))}/><span className="save-state">{pending>0?<Busy text="处理中"/>:<><span className={'status-dot '+(!saved?'pending':'')}/>{saved?'修改已保存':'有修改尚未保存'}</>}</span></div>
 {article.workflow?.[step]?.allowed===false&&<div className="notice amber"><strong>{article.workflow[step].reason}</strong>{article.workflow[step].target!==step&&<button className="text-button" onClick={()=>navigate(article.workflow![step].target)}>前往{LABELS[article.workflow[step].target]}</button>}</div>}
 {job?.native&&<NativeTrace job={job}/>}
 {job?.account_candidate&&<div className="notice amber"><strong>{job.message}</strong><details><summary>查看待处理候选</summary><pre className="editorial-text">{job.partial}</pre></details><button className="text-button" disabled={busy} onClick={()=>run(job.request.stage,{...job.request,revision:article.revision})}>按当前账号参考重新生成</button></div>}
 {job?.status==='needs_input'&&(article.research?.pending||article.stages[job.stage]==='needs_input')&&<div className="notice amber"><strong>{job.message}</strong>{article.research?.pending&&<button className="text-button" onClick={()=>locateIssue()}>处理核实问题</button>}</div>}
 {working&&job&&step!=='sources'&&<div className="job-progress"><div className="row"><LoaderCircle size={17} className="spin"/><div><strong>{job.message}</strong><p>{LABELS[job.stage]||job.stage} · 已用 {seconds} 秒{job.partial?' · 已收到 '+job.partial.length+' 字符':''}</p></div></div><button className="button ghost" onClick={()=>act(async()=>{setJob(await api('/jobs/'+job.id+'/cancel','POST'));update(await api('/articles/'+article.id))})}><Square size={13}/>停止</button></div>}
 {job&&job.stage!=='source_import'&&['failed','conflict','interrupted'].includes(job.status)&&<div className="notice amber"><strong>{job.message}</strong><div className="row">{job.stage==='bound'?<span className="muted">请在对应建议中重新选择“采用限定表述”。</span>:<button className="text-button" onClick={()=>run(job.request.stage,{...job.request,revision:article.revision,resume_job_id:''})}>从此环节重试</button>}{job.partial&&<details><summary>查看已保留的生成结果</summary><pre className="partial-result">{job.partial}</pre></details>}</div></div>}
 {article.stages[step]==='stale'&&<div className="notice amber">前面的内容已改变，这份结果仍保留。请更新本环节，或编辑确认后继续。{step==='outline'&&!!article.outline.sections?.length&&<button className="button secondary" onClick={()=>act(async()=>update(await api('/articles/'+article.id+'/confirm/outline','POST',{revision:article.revision})))}>确认保留当前大纲</button>}</div>}
 <div className="stage-body">{step==='topic'&&<Topics {...common!}/>} {step==='sources'&&<Sources job={job} key={article.id} {...common!} focusRequest={sourceFocus} onFocusHandled={()=>setSourceFocus({token:0})} onContext={(id,explicit)=>selectContext({kind:'source',id},explicit)}/>} {step==='outline'&&<SynthesisSummary a={article}/>} {step==='outline'&&<OutlinePanel {...common!} onContext={(id,explicit)=>selectContext({kind:'section',id},explicit)}/>} {(step==='write'||step==='review')&&<><div className="article-title-edit"><Field label="文章标题" value={article.title} onCommit={v=>save({title:v},'write')}/></div><Suspense fallback={<Busy text="正在打开编辑器"/>}><Editor key={article.id} sources={article.sources} onSourceSave={s=>save(current=>({sources:current.sources.map(x=>x.id===s.id?{...x,bibliography:s.bibliography}:x)}),'sources')} onLookup={async(sid,doi)=>{await flushChanges();update(await api(`/articles/${article.id}/sources/${sid}/metadata`,'POST',{revision:articleRef.current!.revision,doi}))}} content={article.content} words={article.brief.words} onSave={s=>save({content:s},'write')} registerFlush={registerFlush} onSelection={setSelected} highlight={highlight}/></Suspense><EditorialPanel a={article} busy={busy} run={run} act={act} update={update} prepare={common!.prepare}/>{!side&&step==='review'&&<ReviewPanel a={article} onDecision={reviewDecision} busy={busy} locate={setHighlight}/>}</>}{step==='visual'&&<VisualPanel {...common!}/>} {step==='layout'&&<LayoutPanel a={article} save={save} act={act} run={run} busy={busy} meta={meta} prepareExport={prepareExport}/>}</div>
 <div className="stage-footer"><button className="button ghost" disabled={step==='topic'} onClick={()=>navigate(STAGES[STAGES.indexOf(step)-1])}><ArrowLeft size={15}/>上一步</button><span>{step==='layout'?'作品与所有修改，保存在本机。':'确认当前内容，按自己的节奏继续。'}</span>{step!=='layout'&&<button className="button secondary" onClick={()=>navigate(STAGES[STAGES.indexOf(step)+1])}>下一步 · {LABELS[STAGES[STAGES.indexOf(step)+1]]}<ArrowRight size={15}/></button>}</div></main>
 {side&&step!=='layout'&&<ContextSidebar key={article.id+':'+step} step={step} tab={sideTab} narrow={narrow} onTab={tab=>changeSidebar({tab})} onClose={()=>changeSidebar({open:false})}>
 {sideTab==='brief'&&<BriefPanel a={article} meta={meta} save={save} onTopic={()=>void navigate('topic')}/>}
 {sideTab==='context'&&step==='topic'&&<BriefPanel a={article} meta={meta} save={save} direction onTopic={()=>void navigate('topic')}/>}
 {sideTab==='context'&&step==='review'&&<ReviewPanel a={article} onDecision={reviewDecision} busy={busy} locate={quote=>{setHighlight(quote);if(narrow)changeSidebar({open:false})}}/>}
 {sideTab==='context'&&step==='write'&&<><div className="assistant-intro"><Sparkles size={23}/><h3>让这一段，更进一步</h3><p>选中正文，告诉 AI 如何调整。先看对比，再应用修改。</p></div><label className="field"><span>已选中的内容</span><textarea value={selected} onChange={e=>setSelected(e.target.value)} placeholder="在左侧正文中选择一段文字…" rows={5}/></label><div className="quick-prompts">{['更简洁','展开解释','更自然','补充适用条件'].map(t=><button key={t} onClick={()=>setInstruction(t)}>{t}</button>)}</div><label className="field"><span>这次如何修改</span><textarea value={instruction} onChange={e=>setInstruction(e.target.value)} placeholder="例如：保留事实，把这段写得更容易理解" rows={3}/></label><button className="button primary full" disabled={busy||!selected.trim()} onClick={()=>run('revise',{selected_text:selected,instruction,chain:false})}><Sparkles size={15}/>生成修改建议</button>{article.suggestions.map(s=><div className="suggestion" key={s.id}><strong>修改建议</strong><p>{s.explanation}</p><details><summary>修改前</summary><blockquote>{s.original}</blockquote></details><Field label="修改后（可以继续编辑）" multiline value={s.replacement} onCommit={v=>{s.replacement=v}}/><div className="row"><button className="button secondary" onClick={()=>act(async()=>{await flushChanges();update(await api(`/articles/${article.id}/suggestions/${s.id}`,'POST',{revision:articleRef.current!.revision,action:'accept',replacement:s.replacement}))})}><Check size={14}/>应用</button><button className="text-button" onClick={()=>act(async()=>update(await api(`/articles/${article.id}/suggestions/${s.id}`,'POST',{revision:article.revision,action:'reject'})))}>放弃</button></div></div>)}</>}
 {sideTab==='context'&&<StageContext a={article} step={step} selection={contextSelection} clear={()=>setContextSelection(null)} inspect={id=>void act(async()=>{await flushChanges();setInspectSource(id)})} locate={locateContext} issue={locateIssue}/>}
 </ContextSidebar>}
 {inspectSource&&article.sources.find(s=>s.id===inspectSource)&&<ReferenceDetails key={article.id+inspectSource} source={article.sources.find(s=>s.id===inspectSource)!} onClose={()=>setInspectSource('')} onSave={s=>save(current=>({sources:current.sources.map(x=>x.id===s.id?s:x)}),'sources')} onLookup={async doi=>{await flushChanges();update(await api(`/articles/${article.id}/sources/${inspectSource}/metadata`,'POST',{revision:articleRef.current!.revision,doi}))}}/>}</div>}
 <input ref={file} hidden type="file" accept=".md,.txt,.docx,.pdf" onChange={e=>{if(e.target.files?.[0])void create(e.target.files[0]);e.target.value=''}}/>
 {showSettings&&cfg&&<Settings initial={cfg} onClose={()=>setShowSettings(false)} onSaved={setCfg}/>}
 {newModal&&<Modal title="开始一篇新文章" onClose={()=>setNewModal(false)}><p className="modal-intro">先给创作一个方向，其他细节可以边写边调整。</p><Select label="常用栏目" value={newColumn} onChange={setNewColumn}><option>运动科学</option><option>运动健康</option><option>AI</option></Select><Field label="想探索的领域" value={newDomain} onCommit={setNewDomain} placeholder="可留空，例如：青少年训练、AI 智能体"/><Field label="指定主题" value={newTopic} onCommit={setNewTopic} placeholder="可留空，让 AI 提供候选选题"/><div className="modal-footer"><span className="muted">默认逐步确认 · 不自动生图</span><button className="button primary" disabled={pending>0} onClick={()=>create()}><Plus size={16}/>创建文章</button></div></Modal>}
 {records&&<Modal title={records.type==='versions'?'历史版本':'调用记录'} onClose={()=>setRecords(null)} wide>{!records.rows.length?<p className="muted">还没有记录。</p>:records.type==='versions'?records.rows.map(v=><div className="record-row" key={v.id}><div><strong>{v.label}</strong><p className="muted">{date(v.created)}</p></div><button className="button secondary" disabled={busy} onClick={()=>act(async()=>{await flushChanges();const current=articleRef.current!;update(await api('/articles/'+current.id+'/restore','POST',{version:v.id,revision:current.revision}));setRecords(null)})}>恢复此版本</button></div>):<><p className="muted">保留各环节调用与用量；服务未返回用量时显示“—”。</p><div className="usage-table"><table><thead><tr><th>环节 / 模型</th><th>输入 / 输出</th><th>状态</th><th>时间</th></tr></thead><tbody>{records.rows.map(u=><tr key={u.id}><td>{LABELS[u.stage]||u.stage}<small>{u.model}</small></td><td>{u.input_tokens??'—'} / {u.output_tokens??'—'}</td><td>{{completed:'已完成',reserved:'请求已发出',unknown:'结果未知',failed:'未完成',cancelled:'已停止'}[String(u.status)]||'状态未知'}</td><td>{date(u.at)}</td></tr>)}</tbody></table></div></>}{records.type==='versions'&&<Pager page={records.page||1} total={records.total||0} pageSize={50} onChange={page=>void showRecords('versions',page)}/>}</Modal>}
 </div>
}
