import {useEffect,useRef,useState} from 'react';
import {api,errorText,date} from './api';
import {Modal,Busy,Select} from './ui';
import NativeTrace from './NativeTrace';
import type {Article,Job} from './types';

type Overview={configured:boolean;credential_id:string;account_revision:number;personas:any[];custom_personas:any[];themes:any[];platforms:any[];online_metrics:any[];bindings:any[];jobs:Job[]};
export default function ExtensionsPanel({article,prepare,refresh,onClose}:{article:Article|null;prepare:()=>Promise<Article|null>;refresh:()=>Promise<void>;onClose:()=>void}){
 const [data,setData]=useState<Overview|null>(null),[tab,setTab]=useState('rewrite'),[error,setError]=useState(''),[pending,setPending]=useState(false),[job,setJob]=useState<Job|null>(null),[jobs,setJobs]=useState<Job[]>([]);
 const [theme,setTheme]=useState({url:'',name:'user-',label:''}),[persona,setPersona]=useState({id:'user-',label:'',base:'industry-observer',description:'',opening_style:'',closing_tendency:'',uncertainty_expressions:'',avoid:''});
 const [targets,setTargets]=useState(['xiaohongshu','douyin']),[wechat,setWechat]=useState({appid:'',secret:''}),[publishKind,setPublishKind]=useState('publish'),[digest,setDigest]=useState(''),[description,setDescription]=useState(''),[preview,setPreview]=useState<any>(null);
 const [day,setDay]=useState(new Date(Date.now()-86400000).toISOString().slice(0,10)),[msgid,setMsgid]=useState('');
 const busy=pending||job?.status==='running'||job?.status==='queued';const poll=useRef(false);
 async function reload(){const d=await api<Overview>('/extensions');setData(d);const rows=article?await api<Job[]>('/articles/'+article.id+'/jobs'):d.jobs;setJobs(rows.filter(j=>j.request.action));setJob(current=>current||rows.find(j=>j.request.action&&['running','queued'].includes(j.status))||null);return d}
 async function act(fn:()=>Promise<unknown>){setPending(true);setError('');try{await fn()}catch(e){setError(errorText(e))}finally{setPending(false)}}
 useEffect(()=>{void act(async()=>{await reload()})},[article?.id]);
 useEffect(()=>{setPreview(null)},[article?.revision,publishKind,digest,description]);
 useEffect(()=>{if(!job||!['running','queued'].includes(job.status))return;const timer=setInterval(()=>{if(poll.current)return;poll.current=true;void (async()=>{const j=await api<Job>('/jobs/'+job.id);setJob(j);if(!['running','queued'].includes(j.status)){await reload();await refresh()}})().catch(e=>setError(errorText(e))).finally(()=>{poll.current=false})},800);return()=>clearInterval(timer)},[job?.id,job?.status]);
 async function start(action:string,extra:Record<string,unknown>={}){const a=await prepare();const current=await reload();const j=await api<Job>('/extensions/actions','POST',{action,article_id:a?.id||'',revision:a?.revision||0,account_revision:current.account_revision,client_id:crypto.randomUUID(),...extra});setJob(j)}
 function download(name:string,text:string){const url=URL.createObjectURL(new Blob([text],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 const input=(label:string,value:string,change:(s:string)=>void,multiline=false)=><label className="field"><span>{label}</span>{multiline?<textarea aria-label={label} rows={4} value={value} onChange={e=>change(e.target.value)}/>:<input aria-label={label} value={value} onChange={e=>change(e.target.value)}/>}</label>;
 const outputs=(j:Job)=><>{!!j.external_receipt&&<details><summary>微信请求回执</summary><pre className="editorial-text">{JSON.stringify(j.external_receipt,null,2)}</pre></details>}{j.result?.outputs?.map((x:any)=><details key={x.platform}><summary>{x.platform==='xiaohongshu'?'小红书':'抖音'} · {x.characters} 字 · 质量提示 {x.quality_score}</summary><pre className="editorial-text">{x.content}</pre><button className="button secondary" onClick={()=>download(x.filename,x.content)}>下载平台稿</button></details>)}{j.result?.max_similarity!==undefined&&<p>与源稿／其他平台最大相似度：{j.result.max_similarity} · {j.result.needs_input?'仍需处理':'通过上游数值检查'}</p>}{j.result?.content&&<><pre className="editorial-text">{j.result.content}</pre><button className="button secondary" onClick={()=>download(j.stage==='draft_read'?'微信草稿副本.md':'效果复盘.md',j.result.content)}>下载副本</button></>}{j.result?.media_id&&<p>微信草稿编号：<code>{j.result.media_id}</code>；请到公众号草稿箱查看。</p>}{j.result?.rows&&<><p>已匹配 {j.result.matched??0} 条统计；未关联的条目不会按标题自动回填。</p>{j.result.unmatched?.map((x:any)=><p key={x.msgid}>{x.title} · 微信文章编号 {x.msgid}</p>)}</>}{j.result?.theme&&<p>主题已加入排版下拉框：{j.result.theme}</p>}</>;
 return <Modal title="上游扩展" wide onClose={onClose}><div className="account-panel">
  <p className="muted">扩展动作单独启动。多平台稿独立保存；微信操作只进入草稿箱，完整制作不会自动推送。</p>
  <nav className="account-tabs" aria-label="上游扩展">{[['rewrite','多平台改写'],['theme','学习排版'],['persona','自定义人格'],['wechat','微信草稿箱'],['stats','在线效果']].map(([id,label])=><button key={id} className={'button '+(tab===id?'secondary':'ghost')} onClick={()=>setTab(id)}>{label}</button>)}</nav>
  {error&&<p className="notice amber" role="alert">{error}</p>}
  {!data?<Busy/>:<>
   {tab==='rewrite'&&<><p>{article?'当前源稿：'+article.title:'请先打开一篇文章。'}按上游平台规范改写，保留人格与来源；使用写作模型，调用会计费。</p>{data.platforms.map(p=><label className="check" key={p.id}><input type="checkbox" checked={targets.includes(p.id)} onChange={e=>setTargets(e.target.checked?[...targets,p.id]:targets.filter(x=>x!==p.id))}/>{p.label}</label>)}<button className="button primary" disabled={busy||!article?.content||!targets.length} onClick={()=>void act(()=>start('rewrite',{platforms:targets}))}>生成独立平台稿</button></>}
   {tab==='theme'&&<><p>读取公开公众号文章中的原始样式，使用上游主题提取器，不调用模型。新主题会加入原有排版选项。</p>{input('公众号排版参考链接',theme.url,url=>setTheme({...theme,url}))}{input('新主题编号',theme.name,name=>setTheme({...theme,name}))}{input('新主题显示名称',theme.label,label=>setTheme({...theme,label}))}<button className="button primary" disabled={busy||!theme.url||!theme.label} onClick={()=>void act(()=>start('theme',theme))}>学习并保存主题</button>{data.themes.map(t=><p key={t.id}>{t.label} · {t.id}</p>)}</>}
   {tab==='persona'&&<><p>以现有人格为基础保存个人版本；保存后可在任务书中选择，不改动上游人格文件。</p><Select label="人格基础" value={persona.base} onChange={base=>setPersona({...persona,base})}>{data.personas.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</Select>{[['id','自定义人格编号'],['label','人格显示名称'],['description','人格与语感'],['opening_style','开头方式'],['closing_tendency','收尾倾向'],['uncertainty_expressions','不确定性表达示例（每行一条）'],['avoid','避免的表达（每行一条）']].map(([key,label])=><div key={key}>{input(label,persona[key as keyof typeof persona],v=>setPersona({...persona,[key]:v}),!['id','label'].includes(key))}</div>)}<button className="button primary" disabled={busy||!persona.label||!persona.description} onClick={()=>void act(async()=>{const d=await reload();const definition:any={description:persona.description};for(const k of ['opening_style','closing_tendency'] as const)if(persona[k])definition[k]=persona[k];for(const k of ['uncertainty_expressions','avoid'] as const)if(persona[k])definition[k]=persona[k].split('\n').filter(Boolean);await api('/extensions/personas','POST',{...persona,definition,revision:d.account_revision});await reload();await refresh()})}>保存自定义人格</button>{data.custom_personas.map(p=><p key={p.id}>{p.label} · {p.id}<button className="text-button" onClick={()=>setPersona({id:p.id,label:p.label,base:p.id,description:p.definition.description,opening_style:p.definition.opening_style||'',closing_tendency:p.definition.closing_tendency||'',uncertainty_expressions:(p.definition.uncertainty_expressions||[]).join('\n'),avoid:(p.definition.avoid||[]).join('\n')})}>编辑人格</button></p>)}</>}
   {tab==='wechat'&&<><details open={!data.configured}><summary>公众号连接 · {data.configured?'已保存凭证':'尚未配置'}</summary><p>需要公众号提供相应接口权限和网络白名单。凭证在本机加密保存。</p>{input('公众号 AppID',wechat.appid,appid=>setWechat({...wechat,appid}))}<label className="field"><span>公众号 AppSecret</span><input aria-label="公众号 AppSecret" type="password" value={wechat.secret} onChange={e=>setWechat({...wechat,secret:e.target.value})}/></label><button className="button secondary" disabled={busy||!wechat.appid||!wechat.secret} onClick={()=>void act(async()=>{await api('/extensions/wechat','PUT',{...wechat,credential_id:data.credential_id});setWechat({appid:'',secret:''});setPreview(null);await reload()})}>保存公众号连接</button>{data.configured&&<button className="text-button" disabled={busy} onClick={()=>void act(async()=>{await api('/extensions/wechat','PUT',{remove:true,credential_id:data.credential_id});setPreview(null);await reload()})}>移除公众号凭证</button>}</details>
    <Select label="草稿类型" value={publishKind} onChange={setPublishKind}><option value="publish">文章草稿</option><option value="image_post">图片帖草稿</option></Select>{publishKind==='publish'?input('微信摘要',digest,setDigest,true):input('图片帖说明',description,setDescription,true)}<button className="button secondary" disabled={busy||!article} onClick={()=>void act(async()=>{const a=await prepare();if(a)setPreview(await api('/extensions/preview','POST',{article_id:a.id,action:publishKind,digest,description}))})}>查看推送预览</button>
    {preview&&<div className="service-card"><p>{preview.title} · r{preview.revision} · 采用图片 {preview.images} 张</p>{publishKind==='publish'&&<p>微信摘要：{preview.digest}</p>}{preview.issues.map((x:string)=><p className="notice amber" key={x}>{x}</p>)}<iframe title="微信推送预览" sandbox="" srcDoc={preview.html} style={{width:'100%',height:360,border:0}}/><button className="button primary" disabled={busy||!data.configured||!!preview.issues.length} onClick={()=>void act(()=>start(publishKind,{preview_hash:preview.preview_hash,digest,description}))}>{publishKind==='publish'?'将此文章推送到微信草稿箱':'将采用图片推送为图片帖'}</button></div>}
    {article?.extensions?.filter(x=>x.action==='publish'&&x.result?.media_id).map(x=><p key={x.job_id}>草稿 {x.result.media_id}<button className="text-button" disabled={busy||!data.configured} onClick={()=>void act(()=>start('draft_read',{media_id:x.result.media_id}))}>读取微信草稿副本</button></p>)}</>}
   {tab==='stats'&&<><p>先明确关联微信统计文章编号。草稿编号与统计编号不同，同名文章不会自动匹配。缺少凭证时仍可复盘已有本地记录。</p>{input('微信统计文章编号（msgid）',msgid,setMsgid)}<button className="button secondary" disabled={busy||!article||!msgid} onClick={()=>void act(async()=>{const d=await reload();await api('/extensions/bindings','POST',{revision:d.account_revision,article_id:article!.id,msgid});await reload()})}>关联当前文章</button><label className="field"><span>文章群发日期</span><input aria-label="文章群发日期" type="date" value={day} onChange={e=>setDay(e.target.value)}/></label><div className="row wrap"><button className="button primary" disabled={busy||!article||!data.configured||!day} onClick={()=>void act(()=>start('stats',{date:day}))}>拉取并回填在线效果</button><button className="button secondary" disabled={busy||!article} onClick={()=>void act(()=>start('stats_review'))}>复盘已有数据（AI）</button></div>{!data.configured&&<p className="notice">在线拉取需要配置公众号连接。</p>}{data.bindings.map(x=><p key={x.msgid}>{x.title} · {x.msgid}</p>)}{data.online_metrics.map((x,i)=><p key={i}>{x.msgid} · {x.observed_at}：阅读 {x.stats.read_count??'未知'}，分享 {x.stats.share_count??'未知'}，点赞 {x.stats.like_count??'未知'}</p>)}</>}
   {job&&<div className="notice"><p>{busy?<Busy text={job.message}/>:job.message}</p>{['running','queued'].includes(job.status)&&<button className="button secondary" onClick={()=>void act(async()=>setJob(await api('/jobs/'+job.id+'/cancel','POST')))}>停止扩展动作</button>}{outputs(job)}{job.native?.id&&<NativeTrace job={job}/>}</div>}
   <details><summary>扩展任务记录</summary>{jobs.map(j=><details key={j.id}><summary>{j.stage} · {date(j.created)} · {j.status}</summary><p>{j.message}</p>{outputs(j)}{j.native?.id&&<NativeTrace job={j}/>}</details>)}</details>
  </>}
 </div></Modal>;
}
