import ResearchDetails from './ResearchDetails';
import MaterialList,{readView,remember} from './MaterialList';
import ReferenceDetails from './ReferenceDetails';
import {useEffect,useRef,useState} from 'react';
import {BookOpen,Search,Upload,Link as LinkIcon,Plus,Check,ArrowRight,RefreshCw,FileText,ExternalLink,GripVertical,Trash2,ImagePlus,Download,Copy,Smartphone,Sparkles,MessageSquare,CheckCheck,AlertCircle,Lightbulb,Scissors} from 'lucide-react';
import {api} from './api';
import {type Article,type Save,type Meta,type Job} from './types';
import {Field,Select,Toggle,Empty,Tag,Modal,Busy} from './ui';

export type Action=(fn:()=>Promise<void>)=>Promise<void>;
export type Run=(stage:string,extra?:Record<string,unknown>)=>Promise<void>;
type Common={onJob:(j:Job)=>void;a:Article;save:Save;act:Action;update:(a:Article)=>void;run:Run;busy:boolean};

export function Topics({a,save,act,update,run,busy}:Common){
 const [topic,setTopic]=useState(a.brief.topic);const [hot,setHot]=useState<any>(null);const [loading,setLoading]=useState(false);
 useEffect(()=>setTopic(a.brief.topic),[a.brief.topic]);
 const choose=(title:string)=>act(async()=>update(await api('/articles/'+a.id+'/topic','POST',{revision:a.revision,title})));
 return <><div className="topic-input"><div><span className="eyebrow">从一个好问题开始</span><h2>今天，想写点什么？</h2><p>探索新的角度，或带着一个确定的主题出发。</p></div><div className="row"><input aria-label="指定文章主题" placeholder="直接输入主题，例如：力量训练如何帮助跑者？" value={topic} onChange={e=>setTopic(e.target.value)}/><button className="button secondary" disabled={!topic.trim()||busy} onClick={()=>choose(topic)}>采用主题<ArrowRight size={15}/></button></div></div>
 <div className="row between section-label"><h3>候选选题 <span className="count">{a.topics.length||'—'}</span></h3><button className="text-button" disabled={busy} onClick={()=>run('topic')}><RefreshCw size={14}/>{a.topics.length?'换一批选题':'生成 10 个选题'}</button></div>
 {!a.topics.length?<Empty icon={<Lightbulb size={30}/>} title="你的下一个选题，从这里开始" description={`基于「${a.brief.domain||a.brief.column}」寻找角度。你可以先在右侧补充领域、读者和写作偏好。`}><button className="button primary" disabled={busy} onClick={()=>run('topic')}><Sparkles size={16}/>寻找选题灵感</button></Empty>:<div className="topics-grid">{a.topics.map((t,i)=><article key={i} className={'topic-card '+(a.brief.topic===t.title?'selected':'')}><div className="row between"><span className="topic-number">{String(i+1).padStart(2,'0')}</span>{i===0&&<Tag tone="green">优先推荐</Tag>}</div><h3>{t.title}</h3><p>{t.angle}</p><div className="topic-reason">{t.reason}</div>{t.audience&&<small className="muted">适合：{t.audience}</small>}<div className="row between"><span className="muted">{t.source_ids?.length?`${t.source_ids.length} 条关联资料`:'需要补充资料'}</span><button className={'button '+(a.brief.topic===t.title?'secondary':'ghost')} disabled={busy} onClick={()=>choose(t.title)}>{a.brief.topic===t.title?<><Check size={14}/>已采用</>:<>就写这个<ArrowRight size={14}/></>}</button></div></article>)}</div>}
 <details className="hotspots"><summary>看看公开热点</summary><p className="muted">热点提供灵感，不代表事实已核实，也不等同于你所在领域的阅读需求。</p><button className="button secondary" disabled={loading} onClick={()=>{setLoading(true);void act(async()=>setHot(await api('/hotspots'))).finally(()=>setLoading(false))}}>{loading?<Busy text="正在读取热点"/>:'读取公开热点'}</button>{hot&&(hot.items?.length?<div className="hotspot-list">{hot.items.map((h:any,i:number)=><button key={i} onClick={()=>setTopic(h.title)}><span>{i+1}</span>{h.title}<small>{h.source}</small></button>)}</div>:<p className="muted">暂未读取到公开热点，可手动填写主题或生成常青选题。</p>)}</details></>
}

export function Sources({a,save,act,update,run,busy,onJob,focusToken=0,onFocusHandled}:Common&{focusToken?:number;onFocusHandled?:()=>void}){
 const viewKey="materials-tab:"+a.id;
 const [tab,setTab]=useState(()=>readView(viewKey,{tab:a.research?.pending?"results":"materials"}).tab);
 const [summaryOpen,setSummaryOpen]=useState(false);
 const [focus,setFocus]=useState<{token:number;id?:string}>({token:0});const [supplied,setSupplied]=useState(false);const [attachmentIds,setAttachmentIds]=useState<string[]>(()=>readView("materials-supply:"+a.id,{ids:[] as string[]}).ids);
 const selectTab=(tab:string)=>{setTab(tab);remember(viewKey,{tab})};
 const locate=(id?:string)=>{selectTab("results");setFocus({token:Date.now(),id})};
 useEffect(()=>{if(focusToken){locate();onFocusHandled?.()}},[focusToken]);
 const [mode,setMode]=useState('');const [title,setTitle]=useState('');const [text,setText]=useState('');const [url,setUrl]=useState('');const [query,setQuery]=useState('');const [inspect,setInspect]=useState<string|null>(null);const file=useRef<HTMLInputElement>(null);
 async function upload(f:File){const body=new FormData();body.append('file',f);body.append('revision',String(a.revision));await act(async()=>{update(await api('/articles/'+a.id+'/sources/file','POST',body));setSupplied(attachmentIds.length>0)})}
 const selected=a.sources.filter(s=>s.selected).length;
 useEffect(()=>setQuery(''),[a.id]);
 const research=a.research;const researchCurrent=research&&!research.stale;
 const evidenceCurrent=a.stages.sources==='done'&&a.evidence.summary;
 const summary=evidenceCurrent?a.evidence.summary:researchCurrent?research.summary:'';
 const gaps=(research?.issues||[]).filter(x=>x.kind==='blocking'&&x.status==='open').map(x=>x.text);

 return <>{mode==='supplement'&&<Modal title="补充核实资料" onClose={()=>setMode('')}><p>材料会关联所选问题；添加后请点击“AI 核实”，上传成功不代表已核实。</p><div className="row"><button className="button secondary" onClick={()=>{setMode('');file.current?.click()}}>上传文件</button><button className="button secondary" onClick={()=>setMode('url')}>添加链接</button><button className="button secondary" onClick={()=>setMode('text')}>粘贴文字</button></div></Modal>}<div className="source-search"><Search size={18}/><input aria-label="补充检索要求" value={query} onChange={e=>setQuery(e.target.value)} placeholder="可选：补充需要查找或核实的问题，留空按文章主题整理…"/><button className="button primary" disabled={busy||!a.brief.topic} onClick={()=>{selectTab('results');void run('sources',{instruction:query})}}>查找并整理资料</button></div><div className="row wrap source-actions"><button className="button secondary" disabled={busy} onClick={()=>file.current?.click()}><Upload size={15}/>上传文件</button><button className="button secondary" onClick={()=>setMode('url')}><LinkIcon size={15}/>添加链接</button><button className="button secondary" onClick={()=>setMode('text')}><Plus size={15}/>粘贴文字</button><span className="muted">PDF / Word / Markdown / TXT / BibTeX / RIS · 20 MB 内</span><input ref={file} type="file" hidden accept=".pdf,.docx,.md,.txt,.bib,.ris" onChange={e=>{if(e.target.files?.[0])void upload(e.target.files[0]);e.target.value=''}}/></div>
 <div className="material-overview"><span>已采用 {selected} / {a.sources.length} 条素材</span><button className="text-button" onClick={()=>locate()}>{research?.stale?'待复核':'待处理'} {gaps.length} 项</button><Tag tone={research?.stale?"amber":""}>{research?.stale?"资料需要更新":summary?"资料已整理":"尚未整理"}</Tag></div>
 {supplied&&<div className="notice"><span>资料已添加，尚需核实。</span><button className="text-button" onClick={()=>locate(attachmentIds[0])}>返回对应核实问题</button></div>}
 <div className="material-tabs" role="tablist" aria-label="素材页面"><button role="tab" aria-selected={tab==="results"} onClick={()=>selectTab("results")}>资料整理结果</button><button role="tab" aria-selected={tab==="materials"} onClick={()=>selectTab("materials")}>本篇素材 · {a.sources.length}</button></div>
 <div role="tabpanel" aria-label="资料整理结果" hidden={tab!=="results"}>
 {(summary||research||a.evidence.summary)?<section className="research-result source-card"><div className="row between"><h3>资料整理结果</h3><Tag tone={gaps.length||!summary?'amber':'green'}>{!summary?'需要更新':gaps.length?'待处理核心问题':'已整理'}</Tag></div>
 {summary?<><p className={summaryOpen?"summary-full":"preview-clamp summary-preview"}>{summary}</p><button className="text-button" aria-expanded={summaryOpen} onClick={()=>setSummaryOpen(v=>!v)}>{summaryOpen?"收起整理总结":"展开完整整理总结"}</button></>:<p className="muted">材料或主题已改变，请重新整理。历史结果仍保留，但不会作为当前结论展示。</p>}

 {a.evidence.claims?.length>0&&<details><summary>查看主张与证据关联{!evidenceCurrent?'（历史结果，待更新）':''}</summary>{a.evidence.claims.map((c:any)=><div className="claim" key={c.id}><Tag tone={c.status==='unsupported'?'amber':'green'}>{c.status==='unsupported'?'缺少支持':c.type==='fact'?'事实':'推断 / 观点'}</Tag><p>{c.text}</p><small>{c.source_ids.join(' · ')} {c.boundary}</small></div>)}</details>}
 {research&&<ResearchDetails a={a} busy={busy} act={act} update={update} onJob={onJob} run={run} focus={focus} onSupply={ids=>{setAttachmentIds(ids);remember('materials-supply:'+a.id,{ids});setSupplied(false);setMode('supplement')}}/>}
 </section>:<p className="muted">尚无整理结果。添加素材后，点击“查找并整理资料”。</p>}</div>
 <div role="tabpanel" aria-label="本篇素材" hidden={tab!=="materials"}><MaterialList key={a.id} a={a} save={save} busy={busy} act={act} inspect={setInspect}/></div>
 {mode&&mode!=='supplement'&&<Modal title={mode==='url'?'添加网页资料':'添加文字素材'} onClose={()=>setMode('')}>{mode==='url'?<Field label="网页链接" value={url} onCommit={setUrl} placeholder="https://…"/>:<><Field label="素材名称" value={title} onCommit={setTitle} placeholder="例如：我的训练观察"/><Field label="素材正文" multiline value={text} onCommit={setText} placeholder="粘贴文字，也可以记录你真实的经历和看法…"/></>}<div className="modal-footer"><span className="muted">材料只用于本篇文章</span><button className="button primary" disabled={busy} onClick={()=>act(async()=>{update(await api('/articles/'+a.id+'/sources/'+mode,'POST',{revision:a.revision,title,text,url}));setMode('');setText('');setUrl('');setSupplied(attachmentIds.length>0)})}>添加素材</button></div></Modal>}
 {inspect&&a.sources.find(x=>x.id===inspect)&&<ReferenceDetails key={inspect} source={a.sources.find(x=>x.id===inspect)!} onClose={()=>setInspect(null)} onSave={s=>save({sources:a.sources.map(x=>x.id===s.id?s:x)},'sources')} onLookup={async doi=>update(await api(`/articles/${a.id}/sources/${inspect}/metadata`,'POST',{revision:a.revision,doi}))}/>}

 </>
}

export function OutlinePanel({a,save,run,busy}:Common){
 const drag=useRef<number|null>(null);const outline=a.outline;
 const change=(key:string,value:any)=>void save({outline:{...outline,[key]:value}},'outline');
 function changeSection(id:string,key:string,value:any){change('sections',outline.sections?.map(s=>s.id===id?{...s,[key]:value}:s))}
 return !outline.sections?.length?<Empty icon={<FileText size={30}/>} title="先想清楚，再动笔" description="让大纲明确文章要回答的问题、核心观点和每一节的证据。生成后可以逐段修改、拖动排序。"><button className="button primary" disabled={busy||a.workflow?.outline.allowed===false} onClick={()=>run('outline')}><Sparkles size={16}/>生成文章大纲</button></Empty>:<><div className="thesis-card"><span className="eyebrow">文章的核心判断</span><Field label="主张" multiline value={outline.thesis||''} onCommit={v=>change('thesis',v)}/><Field label="读者真正的问题" value={outline.reader_question||''} onCommit={v=>change('reader_question',v)}/></div><div className="row between section-label"><h3>章节安排</h3><span className="muted">拖动左侧手柄调整顺序</span></div>{outline.sections.map((s,i)=><article className="outline-card" key={s.id} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(drag.current===null)return;const list=[...outline.sections!];const [item]=list.splice(drag.current,1);list.splice(i,0,item);change('sections',list);drag.current=null}}><div className="row"><span draggable className="drag-handle" onDragStart={()=>{drag.current=i}}><GripVertical size={18}/></span><span className="topic-number">{String(i+1).padStart(2,'0')}</span><div className="grow"><Field label="章节标题" value={s.title} onCommit={v=>changeSection(s.id,'title',v)}/></div><button className="icon-button" disabled={busy} title="重生成本节" onClick={()=>run('outline',{section_id:s.id,chain:false})}><RefreshCw size={15}/></button><button className="icon-button" title="删除本节" disabled={outline.sections!.length<=1} onClick={()=>change('sections',outline.sections?.filter(x=>x.id!==s.id))}><Trash2 size={15}/></button></div><Field label="这一节推进什么" value={s.purpose} onCommit={v=>changeSection(s.id,'purpose',v)}/><Field label="主要内容（每行一项）" multiline value={s.points.join('\n')} onCommit={v=>changeSection(s.id,'points',v.split('\n').filter(Boolean))}/></article>)}<button className="button secondary" onClick={()=>change('sections',[...outline.sections!,{id:crypto.randomUUID().slice(0,8),title:'新增章节',purpose:'',points:[],claim_ids:[]}])}><Plus size={15}/>增加章节</button><details className="brief-detail"><summary>文章任务书：交付、反方与边界</summary><Field label="读者最终获得什么" multiline value={outline.takeaway||''} onCommit={v=>change('takeaway',v)}/><Field label="反方观点 / 替代解释" multiline value={outline.counterpoint||''} onCommit={v=>change('counterpoint',v)}/><Field label="适用边界" multiline value={outline.boundary||''} onCommit={v=>change('boundary',v)}/></details></>
}

function IssueCard({issue,a,act,update,locate}:{issue:any;a:Article;act:Action;update:(a:Article)=>void;locate:(quote:string)=>void}){
 const [replacement,setReplacement]=useState(issue.suggestion);return <article className={'issue-card '+issue.status}><div className="row between"><Tag tone={issue.severity==='blocker'?'amber':''}>{issue.severity==='blocker'?'需要核实':issue.severity==='major'?'建议修改':'表达优化'}</Tag><button className="text-button" onClick={()=>locate(issue.quote)}>定位原文<ArrowRight size={13}/></button></div><p>{issue.reason}</p><blockquote>{issue.quote||'整体问题，请对照正文修改'}</blockquote>{issue.status==='pending'?<><Field label="建议替换为（可以先修改）" multiline value={replacement} onCommit={setReplacement}/><small className="muted">{issue.source_ids?.join(' · ')}</small><div className="row"><button className="button secondary" onClick={()=>act(async()=>update(await api(`/articles/${a.id}/review/${issue.id}`,'POST',{revision:a.revision,action:'accept',replacement})))}><Check size={14}/>接受修改</button><button className="text-button" onClick={()=>act(async()=>update(await api(`/articles/${a.id}/review/${issue.id}`,'POST',{revision:a.revision,action:'reject'})))}>保留原文</button></div></>:<Tag tone="green">{issue.status==='accepted'?'已应用 · 请复审':'已保留原文'}</Tag>}</article>
}

export function ReviewPanel({a,act,update,locate}:{a:Article;act:Action;update:(a:Article)=>void;locate:(quote:string)=>void}){
 const review=a.review;return <div className="review-panel">{review.summary?<><div className={'review-summary '+(review.decision==='pass'&&a.stages.review==='done'?'pass':'')}><div className="row"><CheckCheck size={20}/><strong>{a.stages.review==='stale'?'正文已更新，需要复审':review.decision==='pass'?'AI 审核通过':'还有内容值得打磨'}</strong></div><p>{review.summary}</p><small>AI 审核是辅助判断；具体事实请对照来源。</small></div>{review.issues?.map((i:any)=><IssueCard key={i.id+review.content_revision} issue={i} a={a} act={act} update={update} locate={locate}/>)}{review.digest&&<details><summary>标题、摘要与标签</summary><p>{review.title}</p>{review.alt_titles?.map((t:string,i:number)=><p key={i} className="muted">备选 {i+1}：{t}</p>)}<p>{review.digest}</p><div className="row wrap">{review.tags?.map((t:string)=><Tag key={t}>{t}</Tag>)}</div></details>}<details><summary>查看辅助评分与机械检查</summary><pre className="detail-json">{JSON.stringify({编辑维度:review.dimensions,机械提示:review.tool_hints},null,2)}</pre></details></>:<Empty icon={<MessageSquare size={26}/>} title="多一个编辑视角" description="审核会对照本篇资料检查事实、观点、深度和表达，并把修改意见定位到原文。"/>}</div>
}

export function VisualPanel({a,save,act,update,run,busy}:Common){
 const file=useRef<HTMLInputElement>(null);const [role,setRole]=useState('article');
 return <><div className="visual-intro"><div><h3>让图片为内容服务</h3><p className="muted">可以上传自己的图片，也可以按需生成。排版不会自动触发生图。</p></div><Toggle checked={a.visual.enabled} label="启用 AI 配图" onChange={v=>void save({visual:{...a.visual,enabled:v}},'preferences')}/></div>
 {a.visual.enabled&&<div className="form-grid three"><Field label="图片数量" type="number" value={a.visual.count} min={1} max={6} onCommit={v=>void save({visual:{...a.visual,count:Number(v)}},'preferences')}/><Select label="图片比例" value={a.visual.size} onChange={v=>void save({visual:{...a.visual,size:v}},'preferences')}><option value="1536x1024">横图 · 1536 × 1024</option><option value="1024x1024">方图 · 1024 × 1024</option><option value="1024x1536">竖图 · 1024 × 1536</option></Select><Field label="本篇图片预算 / 元" type="number" value={a.visual.budget} onCommit={v=>void save({visual:{...a.visual,budget:Number(v)}},'preferences')}/></div>}
 <div className="row wrap"><button className="button primary" disabled={busy||!a.visual.enabled} onClick={()=>run('visual')}><Sparkles size={16}/>生成配图方案</button><button className="button secondary" onClick={()=>{setRole('cover');file.current?.click()}}><Upload size={15}/>上传封面</button><button className="button secondary" onClick={()=>{setRole('article');file.current?.click()}}><ImagePlus size={15}/>上传插图</button><input hidden ref={file} type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{if(e.target.files?.[0]){const f=new FormData();f.append('file',e.target.files[0]);f.append('revision',String(a.revision));f.append('role',role);void act(async()=>update(await api('/articles/'+a.id+'/images/upload','POST',f)))}e.target.value=''}}/></div>
 {a.image_plans.length>0&&<div className="image-plans">{a.image_plans.map((p,i)=><section key={p.id} className="image-plan"><div className="row between"><h3>{p.role==='cover'?'封面方案':`插图方案 ${i}`}</h3><Tag>待生成</Tag></div><Field label="图片提示词" multiline value={p.prompt} onCommit={v=>void save({image_plans:a.image_plans.map(x=>x.id===p.id?{...x,prompt:v}:x)},'preferences')}/><Field label="图注" value={p.caption} onCommit={v=>void save({image_plans:a.image_plans.map(x=>x.id===p.id?{...x,caption:v}:x)},'preferences')}/><button className="button secondary" disabled={busy||!a.visual.enabled} onClick={()=>run('image',{image_id:p.id,chain:false})}>生成这一张</button></section>)}</div>}
 {a.images.length?<div className="image-gallery">{a.images.map(im=><article className="image-card" key={im.id}><img src={`/api/articles/${a.id}/assets/${im.filename}`} alt={im.caption||'文章配图'}/><div className="image-meta"><div className="row between"><Toggle checked={im.selected} label="用于排版" onChange={v=>void save({images:a.images.map(x=>x.id===im.id?{...x,selected:v}:x)},'visual')}/><button className="icon-button" title="移除图片" onClick={()=>void save({images:a.images.filter(x=>x.id!==im.id)},'visual')}><Trash2 size={15}/></button></div><Select label="用途" value={im.role} onChange={v=>void save({images:a.images.map(x=>x.id===im.id?{...x,role:v}:x)},'visual')}><option value="cover">封面</option><option value="article">内文插图</option></Select><Field label="图注" value={im.caption} onCommit={v=>void save({images:a.images.map(x=>x.id===im.id?{...x,caption:v}:x)},'visual')}/>{im.role==='article'&&<Select label="放在章节之后" value={im.after_heading||''} onChange={v=>void save({images:a.images.map(x=>x.id===im.id?{...x,after_heading:v}:x)},'visual')}><option value="">文章末尾</option>{[...a.content.matchAll(/^#{1,6}\s+(.+)$/gm)].map((m,i)=><option key={i} value={m[1]}>{m[1]}</option>)}</Select>}</div></article>)}</div>:<Empty icon={<ImagePlus size={30}/>} title="配图可以晚一点决定" description="正文独立保存。先完成文章，随时回来添加封面和插图。"/>}</>
}

export function LayoutPanel({a,save,act,run,busy,meta,prepareExport}:{a:Article;save:Save;act:Action;run:Run;busy:boolean;meta:Meta;prepareExport:(open?:boolean)=>Promise<any>}){
 const [preview,setPreview]=useState<{html:string;body:string;plaintext:string;references:any[]}|null>(null);const [loading,setLoading]=useState(false);const [copied,setCopied]=useState(false);const seq=useRef(0);
 useEffect(()=>{const n=++seq.current;const t=setTimeout(()=>{if(!a.content)return;setLoading(true);void act(async()=>{const p=await api('/articles/'+a.id+'/preview','POST');if(n===seq.current)setPreview(p)}).finally(()=>{if(n===seq.current)setLoading(false)})},350);return()=>clearTimeout(t)},[a.revision]);
 const [archive,setArchive]=useState<{path:string;revision:number}|null>(null);
 async function download(kind:string){const info=await prepareExport();setArchive(info);const link=document.createElement('a');link.href=`/api/articles/${a.id}/exports/${info.digest}/${kind}`;link.download='';link.click()}
 const change=(k:string,v:any)=>void save({layout:{...a.layout,[k]:v}},'layout');
 async function copy(){if(!preview)return;await navigator.clipboard.write([new ClipboardItem({'text/html':new Blob([preview.body],{type:'text/html'}),'text/plain':new Blob([preview.plaintext],{type:'text/plain'})})]);setCopied(true);setTimeout(()=>setCopied(false),3000)}
 return <div className="layout-workspace"><div className="layout-controls"><span className="eyebrow">文章的最后一公里</span><h3>让好内容，读起来更舒服</h3><Select label="排版主题" value={a.layout.theme} onChange={v=>change('theme',v)}>{meta.themes.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</Select><div className="theme-swatches">{meta.themes.slice(0,12).map(t=><button title={t.name} aria-label={t.name} key={t.id} style={{background:t.colors.primary||'#243e38'}} className={a.layout.theme===t.id?'selected':''} onClick={()=>change('theme',t.id)}/>)}</div><div className="form-grid"><Field label="正文字号" type="number" min={12} max={24} value={a.layout.font_size} onCommit={v=>change('font_size',Number(v))}/><Field label="行距倍数" type="number" value={a.layout.line_height} onCommit={v=>change('line_height',Number(v))}/></div><Field label="段落间距 / px" type="number" value={a.layout.paragraph_gap} onCommit={v=>change('paragraph_gap',Number(v))}/><Field label="署名" value={a.layout.author} placeholder="可选" onCommit={v=>change('author',v)}/><button className="button secondary full" disabled={busy||!a.content} onClick={()=>run('layout_advice',{chain:false})}><Sparkles size={15}/>AI 排版建议</button>{a.layout_advice&&<div className="layout-advice">{a.layout_advice}</div>}<div className="export-group"><button className="button primary full" disabled={!preview} onClick={()=>act(copy)}>{copied?<Check size={16}/>:<Copy size={16}/>} {copied?'已复制':'复制公众号排版'}</button><button className="button secondary full" disabled={busy||!a.content} onClick={()=>act(()=>download('zip'))}><Download size={16}/>下载完整文章包</button><div className="row"><button className="text-button" disabled={busy||!a.content} onClick={()=>act(()=>download('md'))}>Markdown</button><span className="muted">·</span><button className="text-button" disabled={busy||!a.content} onClick={()=>act(()=>download('html'))}>HTML</button></div></div>{archive&&<div className="small-text"><p style={{overflowWrap:'anywhere'}}>已归档 r{archive.revision}：{archive.path}</p><button className="text-button" disabled={busy} onClick={()=>act(async()=>setArchive(await prepareExport(true)))}>打开归档文件夹</button></div>}<p className="muted small-text">完整文章包含图片请下载 ZIP。复制到公众号后，本地图片需在微信编辑器中上传。</p>{preview?.references.some(r=>!r.complete)&&<div className="notice amber small-text">部分文献信息待补全。请点击编辑器中的引用或素材，核对作者、年份及出处。</div>}{a.stages.review!=='done'&&<div className="notice amber small-text">当前正文尚未通过最新审核。可导出备份，正式使用前请核对。</div>}</div><div className="preview-area"><div className="row between preview-label"><span><Smartphone size={15}/>手机阅读预览</span>{loading?<Busy text="更新预览"/>:<span className="muted">375 px</span>}</div><div className="phone-frame"><div className="phone-status">9:41 <span>● ▰</span></div><div className="phone-title">{a.title}</div>{preview?<iframe title="公众号排版预览" sandbox="" srcDoc={preview.html}/>:<div className="preview-empty">写好正文后，排版会出现在这里。</div>}</div></div></div>
}
