import {useState} from 'react';
import type {Source} from './types';
import {Field,Select,Modal} from './ui';

export default function ReferenceDetails({source,onSave,onClose,onLookup,onIdentify}:{source:Source;onSave:(s:Source)=>Promise<unknown>;onClose:()=>void;onLookup?:(doi:string)=>Promise<unknown>;onIdentify?:()=>Promise<unknown>}){
 const [m,setM]=useState<Record<string,any>>({...{title:source.title,url:source.url,doi:source.doi||'',document_type:source.url?'EB':'',access_date:(source.retrieved_at||'').slice(0,10)},...source.bibliography});
 const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const change=(k:string,v:any)=>setM(x=>({...x,[k]:v}));
 const authors=(m.authors||[]).map((a:any)=>typeof a==='string'?a:[a.family,a.given].filter(Boolean).join(', ')||a.literal).join('; ');
 async function act(fn:()=>Promise<unknown>){setBusy(true);setError('');try{await fn();onClose()}catch(e){setError(e instanceof Error?e.message:'保存失败')}finally{setBusy(false)}}
 return <Modal title="引用详情与文献信息" onClose={onClose} wide><p className="muted">按原始文献填写；缺失内容可留空，排版会提示待补全。GB/T 7714—2025 顺序编码制。</p><Field label="题名" value={m.title||''} onCommit={v=>change('title',v)}/><Field label="作者（分号分隔；西文可用 姓, 名）" value={authors} onCommit={v=>change('authors',v.split(';').map(x=>x.trim()).filter(Boolean).map(x=>{const p=x.split(',');return p.length===2?{family:p[0].trim(),given:p[1].trim()}:x}))}/><div className="form-grid"><Select label="文献类型" value={m.document_type||''} onChange={v=>change('document_type',v)}><option value="">待确认</option><option value="J">期刊论文</option><option value="C">会议论文</option><option value="M">书籍</option><option value="PP">预印本</option><option value="EB">网页</option></Select>{[['venue','期刊或会议'],['year','年份'],['volume','卷'],['issue','期'],['pages','页码'],['article_number','文章号'],['doi','DOI'],['url','原文网址'],['published_date','发表 / 更新日期'],['access_date','访问日期'],['platform','预印本平台'],['version','版本'],['publisher','出版社'],['publication_place','出版地']].map(([k,label])=><Field key={k} label={label} value={m[k]||''} onCommit={v=>change(k,v)}/>)}</div><details open><summary>已定位的证据片段</summary>{source.evidence_spans?.length?source.evidence_spans.map((e,i)=><blockquote key={i}>{e.quote}<p className="muted">{e.claim} · {e.location} · {e.boundary}</p>{e.source_type&&<p>来源类别：{e.source_type}</p>}{e.adoption_reason&&<p>采用理由：{e.adoption_reason}</p>}{e.use_scope&&<p>适用范围：{e.use_scope}</p>}{e.quality&&<p>适用性：{{suitable:'适用',limited:'有限',insufficient:'不足',unassessed:'待评估'}[e.quality]||'待评估'}</p>}</blockquote>):<p className="muted">尚无经原文定位的片段，请核对这条引用支持的判断。</p>}</details><details><summary>来源内容与元数据出处</summary><p>{source.status==='metadata_only'?'仅文献信息，不能支持研究结论':source.status==='abstract_only'?'仅有摘要':'按实际获取内容核对证据'}</p><pre className="source-full">{source.text||'尚未取得正文'}</pre><p className="muted">{source.metadata_provenance?.map((x:any)=>x.provider).join('、')||'用户提供，待核对'}</p></details>{error&&<p role="alert" className="notice amber">{error}</p>}<div className="modal-footer">{onIdentify&&<button className="button secondary" disabled={busy} onClick={()=>act(()=>onIdentify())}>识别文献信息</button>}<button className="button secondary" disabled={busy||!m.doi||!onLookup} onClick={()=>act(()=>onLookup!(m.doi))}>从 DOI 核对信息</button><button className="button primary" disabled={busy} onClick={()=>act(()=>onSave({...source,bibliography:m}))}>保存文献信息</button></div></Modal>
}
