import {useEffect,useRef,useState} from 'react';
import {api} from './api';
import {type Article,type Job,LABELS,type ResearchStats} from './types';
import SearchStrategy from './SearchStrategy';
import {Pager,readView,remember} from './MaterialList';

const STATUS:Record<string,string>={needs_input:'待处理',completed:'已完成',failed:'未完成',cancelled:'已停止',interrupted:'运行中断',conflict:'内容已变化，需重新开始',queued:'等待执行',running:'进行中'};

function Activity({r}:{r:any}){
 const s:ResearchStats|undefined=r.stats;
 return <>{s?<><p>{s.search_requests===0?(s.search_cache_hits?'本次复用已有检索结果':'本次仅核对已有材料'):`本次新增搜索 ${s.search_requests} 次`} · 检查已有材料 {s.existing_checked} 条</p><p>搜索缓存复用 {s.search_cache_hits} 次 · 网页读取尝试 {s.page_attempts} 次 · 页面缓存复用 {s.page_cache_hits} 次</p><p>取得全文 {s.fulltext} 篇 · 取得摘要 {s.abstracts} 篇 · 文献信息查询 {s.metadata_requests} 次（缓存 {s.metadata_cache_hits} 次）</p></>:<p>旧版记录：{r.calls??0} 次调用（可能含文献信息查询），{r.pages??0} 次读取计数；未分别记录成功篇数。</p>}<details><summary>策略与执行记录</summary><SearchStrategy value={r.strategy}/>{r.plan?.reason&&<p>本次判断：{r.plan.reason}</p>}{r.log?.map((x:any,i:number)=><p key={i}>{x.message} {x.query} {x.reason}</p>)}</details></>;
}

export default function ResearchDetails({a,busy,act,update,onJob,run,onSupply,focus,prepare,onInspect}:{a:Article;busy:boolean;act:(fn:()=>Promise<void>)=>Promise<void>;update:(a:Article)=>void;onJob:(j:Job)=>void;run:(stage:string,extra?:Record<string,unknown>)=>Promise<void>;onSupply:(ids:string[])=>void;onInspect:(id:string)=>void;focus?:{token:number;id?:string};prepare:()=>Promise<Article>}){
 const [history,setHistory]=useState<any[]>([]);const [error,setError]=useState('');const [selected,setSelected]=useState<string[]>([]);const lock=useRef(false);const root=useRef<HTMLDivElement>(null);
 const key='materials-issues:'+a.id;const [view,setView]=useState(()=>readView(key,{filter:'pending',page:1,open:[] as string[]}));
 const change=(patch:Partial<typeof view>)=>{if(patch.filter!==undefined||patch.page!==undefined)setSelected([]);setView(old=>{const next={...old,...patch};remember(key,next);return next})};
 const r=a.research;const rows=[...(r?.issues||[])].sort((x,y)=>Number(y.priority==='high')-Number(x.priority==='high'));
 useEffect(()=>{setSelected([]);let active=true;void api<any[]>(`/articles/${a.id}/research/history`).then(v=>{if(active){setHistory(v);setError('')}}).catch(e=>{if(active)setError(String(e))});return()=>{active=false}},[a.id,r?.job_id,a.revision]);
 useEffect(()=>{if(!focus?.token)return;const issue=rows.find(x=>x.id===focus.id)||rows.find(x=>x.kind==='blocking'&&['open','stale'].includes(x.status));if(issue){const filter=!['open','stale'].includes(issue.status)?'handled':'pending';const items=rows.filter(x=>filter==='handled'?!['open','stale'].includes(x.status):['open','stale'].includes(x.status));change({filter,page:Math.floor(items.findIndex(x=>x.id===issue.id)/10)+1,open:[...new Set([...view.open,issue.id])]});setTimeout(()=>root.current?.querySelector('[data-issue="'+issue.id+'"]')?.scrollIntoView({block:'nearest',behavior:'smooth'}),0)}},[focus?.token]);
 if(!r)return null;
 const filtered=rows.filter(x=>view.filter==='handled'?!['open','stale'].includes(x.status):['open','stale'].includes(x.status));const page=Math.min(view.page,Math.max(1,Math.ceil(filtered.length/10)));const visible=filtered.slice((page-1)*10,page*10);const eligible=visible.filter(x=>['open','stale'].includes(x.status)).map(x=>x.id);
 const action=(kind:string,ids:string[])=>{if(lock.current||busy)return;if(kind==='attach'){onSupply(ids);return}lock.current=true;void act(async()=>{const current=await prepare();const result=await api<{article:Article;job:Job|null}>(`/articles/${a.id}/research/issues/actions`,'POST',{revision:current.revision,issue_ids:ids,action:kind==='bound'?'bound_auto':kind,action_id:crypto.randomUUID()});update(result.article);if(result.job)onJob(result.job)}).finally(()=>{lock.current=false})};

 const target=r.resume_stage;const resume=r.resume_job_id;
 return <div className="research-details" ref={root}>{rows.length>0&&<><div className="row between"><h4>创作建议</h4><span className="muted">建议不阻止继续创作；未获支持的判断需要保留限定</span></div>
 <div className="material-toolbar wrap">{[['pending','待处理'],['handled','已处理']].map(([id,label])=><button key={id} className={'button '+((view.filter==='handled'?view.filter:'pending')===id?'secondary':'ghost')} aria-pressed={(view.filter==='handled'?view.filter:'pending')===id} onClick={()=>change({filter:id,page:1})}>{label} · {rows.filter(x=>id==='handled'?!['open','stale'].includes(x.status):['open','stale'].includes(x.status)).length}</button>)}</div>
 {view.filter!=='handled'&&<div className="material-toolbar wrap"><label><input type="checkbox" aria-label="全选当前页待处理项" disabled={busy||!eligible.length} checked={!!eligible.length&&eligible.every(id=>selected.includes(id))} ref={el=>{if(el)el.indeterminate=selected.length>0&&!eligible.every(id=>selected.includes(id))}} onChange={e=>setSelected(e.target.checked?eligible:[])}/>全选当前页待处理项</label><span className="muted">已选 {selected.length} 项</span><button className="text-button" disabled={!selected.length||busy} onClick={()=>setSelected([])}>清空选择</button><button className="button secondary" disabled={busy||!selected.length} onClick={()=>action('verify',selected)}>核实所选问题（{selected.length}）</button><button className="text-button" disabled={busy||!selected.length||r.stale} onClick={()=>action('exclude',selected)}>本篇不使用所选主张（{selected.length}）</button></div>}
 {!filtered.length&&<p className="muted">此分类暂无问题。</p>}{visible.map(x=>{const open=view.open.includes(x.id);return <article className="advice-row research-issue" data-issue={x.id} key={x.id}><div className="row">{['open','stale'].includes(x.status)&&<input type="checkbox" disabled={busy} aria-label={'准备批量处理：'+x.text} checked={selected.includes(x.id)} onChange={e=>setSelected(v=>e.target.checked?[...v,x.id]:v.filter(id=>id!==x.id))}/>}<strong>{x.status==='excluded'?'本篇不使用':x.status==='bounded'||x.status==='waived'?'采用有边界表述':x.status==='stale'?'相关依据已变化':x.status==='resolved'?'已核实':x.priority==='high'?'高优先级':'普通优先级'}</strong><button className="text-button" aria-expanded={open} onClick={()=>change({open:open?view.open.filter(id=>id!==x.id):[...view.open,x.id]})}>{open?'收起问题':'展开问题'}</button></div><p className={open?'':'preview-clamp'}>{x.text}</p>{open&&<>{x.wording&&<p>本篇表述：{x.wording}</p>}{x.resolution&&<p className="muted">核实结果：{x.resolution}</p>}{x.source_ids.length>0&&<div className="advice-sources">{x.source_ids.map(id=><button className="text-button source-reference" key={id} onClick={()=>onInspect(id)}>{a.sources.find(s=>s.id===id)?.title||'来源已删除'}</button>)}</div>}{x.application&&<details><summary>查看限定改动 · {x.application.edits.length} 处</summary><p>{x.application.explanation}</p>{x.application.edits.map((e:any,i:number)=><div key={i}><p className="muted">修改前：{e.original}</p><p>修改后：{e.replacement}</p></div>)}{!!x.application.unapplied.length&&<p className="notice amber">{x.application.unapplied.length} 处未能准确定位，原文已保留，请核对。</p>}{!x.application.edits.length&&<p className="muted">已保存后续写作约束，现有正文未修改。</p>}</details>}<div className="row wrap">{x.status==='resolved'?<span className="muted">已找到对应原文依据</span>:['waived','bounded','excluded'].includes(x.status)?<button className="text-button" disabled={busy} onClick={()=>action('undo',[x.id])}>撤销处理决定</button>:<><button className="button secondary" disabled={busy} onClick={()=>action('verify',[x.id])}>AI 核实</button><button className="text-button" disabled={busy} onClick={()=>action('bound',[x.id])}>采用限定表述</button><button className="text-button" disabled={busy} onClick={()=>action('exclude',[x.id])}>本篇不使用</button><button className="text-button" disabled={busy} onClick={()=>action('attach',[x.id])}>补充资料</button></>}</div></>}</article>})}<Pager page={page} total={filtered.length} onChange={page=>change({page})}/></>}
 {target&&['outline','review','topic'].includes(target)&&resume&&!r.pending&&!r.stale&&a.stages[target]!=='done'&&<button className="button primary" disabled={busy||!a.workflow?.[target]?.allowed} onClick={()=>run(target,{resume_job_id:resume})}>继续{target==='outline'?'生成大纲':LABELS[target]}</button>}
 <details className="research-history"><summary>本次资料核对{r.stale?'（历史结果）':''}</summary><Activity r={r}/></details>
 <details className="research-history"><summary>历次检索与核对 · {history.length} 次任务</summary>{error&&<p role="alert">{error}</p>}{history.map(h=><details key={h.id}><summary>{new Date(h.created).toLocaleString()} · {LABELS[h.stage]||h.stage} · {STATUS[h.status]||h.status}</summary><Activity r={h.research}/></details>)}</details>
 </div>;
}
