import {useEffect,useRef,useState} from 'react';
import SearchStrategy from './SearchStrategy';
import {api,date,errorText} from './api';
import {Field,Select,Toggle,Tag} from './ui';

const labels:Record<string,string>={passed:'可用',failed:'未通过',partial:'仅摘要或片段',running:'进行中',unverified:'尚未验证'};
export default function SearchCheckPanel({save,disabled,configVersion}:{save:()=>Promise<unknown>;disabled:boolean;configVersion:number}){
 const [report,setReport]=useState<any>(null),[column,setColumn]=useState('运动科学'),[topic,setTopic]=useState(''),[free,setFree]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const requestEpoch=useRef(0);
 const active=report&&['running','queued'].includes(report.status);
 useEffect(()=>{let live=true;const epoch=++requestEpoch.current;api('/search/check/latest').then(r=>{if(live&&epoch===requestEpoch.current)setReport(r)}).catch(e=>{if(live)setError(errorText(e))});return()=>{live=false}},[configVersion]);
 useEffect(()=>{if(!active)return;let live=true;const timer=setInterval(()=>api('/search/check/'+report.id).then(r=>{if(live)setReport(r)}).catch(e=>{if(live)setError(errorText(e))}),1200);return()=>{live=false;clearInterval(timer)}},[active,report?.id]);
 async function start(){setBusy(true);setError('');try{await save();const r=await api('/search/check','POST',{column,topic,without_tavily:free});requestEpoch.current++;setReport(r)}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 return <section className="service-card search-check"><div className="row between"><h3>工作台搜索</h3>{report&&<Tag tone={report.passed&&!report.stale?'green':''}>{report.stale?'配置已变化，需重测':active?'正在验证':report.passed?'完整链路已验证':'尚未完全通过'}</Tag>}</div><p>工作台找资料、读取原文，再交给文字模型整理。模型无需自带联网能力。</p><div className="form-grid"><Select label="测试领域" value={column} onChange={setColumn}>{['运动科学','运动健康','AI','自定义'].map(x=><option key={x}>{x}</option>)}</Select><Field label="具体问题（可留空）" value={topic} placeholder="留空使用该领域的测试问题" onCommit={setTopic}/></div><Toggle label="本次测试不使用 Tavily（不改变日常设置）" checked={free} onChange={setFree}/><p className="muted small-text">会真实调用检索与资料整理模型，费用未知时以服务商账单为准。每次最多 8 次搜索、读取 16 个页面，仍受你设定的更低限额约束。</p><div className="row wrap"><button className="button primary" disabled={disabled||busy||!!active||(column==='自定义'&&!topic.trim())} onClick={start}>{busy?'正在启动…':'测试工作台搜索'}</button>{active&&<button className="button secondary" onClick={async()=>{try{await api('/jobs/'+report.id+'/cancel','POST');setReport(await api('/search/check/'+report.id))}catch(e){setError(errorText(e))}}}>停止测试</button>}</div>{error&&<p role="alert" className="notice">{error}</p>}
 {report&&<div aria-live="polite"><p className="muted small-text">最近测试：{date(report.created)} · {report.request.column}{report.request.without_tavily?' · 未使用 Tavily':''}</p><div className="search-check-steps">{[['retrieval','检索'],['reading','原文读取'],['organizing','AI 整理']].map(([key,label])=><div key={key}><strong>{label}</strong><Tag tone={report.steps[key]==='passed'?'green':''}>{labels[report.steps[key]]||'尚未验证'}</Tag></div>)}</div><p>{report.message}{active&&<span className="muted small-text"> · 已用 {Math.max(0,Math.floor((Date.now()-Date.parse(report.created))/1000))} 秒</span>}</p><SearchStrategy value={report.research?.strategy}/>{report.summary&&<p>{report.summary}</p>}{report.evidence?.map((e:any,i:number)=><article className="search-evidence" key={i}><a href={e.url} target="_blank" rel="noreferrer">{e.title}</a><p>{e.claim}</p><blockquote>{e.quote}</blockquote><small>{e.source_status==='retrieved'?'已读原文':e.source_status==='abstract_only'?'仅有研究摘要':'仅搜索片段'} · {e.location} · 引用已逐字定位</small>{e.boundary&&<p className="muted small-text">适用边界：{e.boundary}</p>}</article>)}{report.gaps?.length>0&&<p>仍缺资料：{report.gaps.join('；')}</p>}{report.conflicts?.length>0&&<p>存在争议：{report.conflicts.join('；')}</p>}<details><summary>渠道、用量与详细记录</summary><p>搜索调用 {report.research?.calls||0} 次 · 读取 {report.research?.pages||0} 页。复用缓存时不重复搜索；AI 整理另计用量。</p>{report.research?.log?.map((l:any,i:number)=><p className="small-text" key={i}>{l.channel?`[${l.channel}] `:''}{l.message}{l.query?' · 检索词：'+l.query:''}{l.reason?'：'+l.reason:''}</p>)}{report.usage?.map((u:any)=><p className="muted small-text" key={u.id}>{u.stage==='search'?'搜索':'AI 整理'} · {u.model} · Token {u.input_tokens??'未知'} / {u.output_tokens??'未知'} · {u.estimated_cost==null?'费用未知':`${u.estimated_cost} ${u.currency||'CNY'}`}</p>)}<p className="muted small-text">逐字定位说明引用确实出现在资料中，不等同于对来源和结论完成独立事实核查。</p></details></div>}</section>
}
