import {useState} from 'react';
import {Plus,Trash2,PlugZap,ShieldCheck,Check} from 'lucide-react';
import {api} from './api';
import ModelTests from './ModelTests';
import SearchPreferences from './SearchPreferences';
import {type Settings as Config,type Service,type ModelCard,LABELS} from './types';
import {Modal,Field,Select,Toggle,Busy,Tag} from './ui';

const presets=[['chat','OpenAI 兼容 · 通用文本'],['responses','OpenAI Responses · 文本与工具'],['anthropic','Claude · 原生 Messages']];
export default function Settings({initial,onClose,onSaved}:{initial:Config;onClose:()=>void;onSaved:(c:Config)=>void}){
 const [cfg,setCfg]=useState<Config>(structuredClone(initial));const [tab,setTab]=useState('services');const [busy,setBusy]=useState('');const [notice,setNotice]=useState('');const [models,setModels]=useState<Record<string,string[]>>({});
 const routes=['topic','sources','research','outline','write','review','revise','visual','image','layout_advice'];
 function change(id:string,patch:Partial<Service>){setCfg(c=>({...c,services:c.services.map(s=>s.id===id?{...s,...patch,status:'untested'}:s),route_capabilities:{},model_capabilities:[]}))}
 function search(patch:Partial<Config['search']>){setCfg(c=>({...c,search:{...c.search,...patch}}))}
 function protocol(card:ModelCard,p:string){setCfg(c=>({...c,model_capabilities:[],model_connections:[...(c.model_connections||[]).filter(x=>x.service_id!==card.service_id||x.model!==card.model),{service_id:card.service_id,model:card.model,search_protocol:p}]}))}
 async function test(card:ModelCard,kind:string){await action(kind,async()=>{await save();try{const r=await api(`/services/${card.service_id}/capability-tests`,'POST',{model:card.model,kind,protocol:card.search_protocol});setNotice(r.message)}finally{await reload()}})}
 async function save(){const c=await api<Config>('/settings','PUT',cfg);setCfg(c);onSaved(c);return c}
 async function action(name:string,fn:()=>Promise<void>){setBusy(name);setNotice('');try{await fn()}catch(e){setNotice(e instanceof Error?e.message:'操作未完成，请重试')}finally{setBusy('')}}
 async function reload(){const c=await api<Config>('/settings');setCfg(c);onSaved(c)}
 function add(){const id=crypto.randomUUID();setCfg(c=>({...c,default_service:c.default_service||id,services:[...c.services,{id,name:'APIKEY.FAN',base_url:'https://api.apikey.fan',protocol:'chat',model:'',key_set:false,status:'untested',image_status:'untested',currency:'CNY',max_tokens:8000}]}))}
 return <Modal title="AI 服务与偏好" onClose={onClose} wide><div className="settings-shell"><nav className="settings-tabs">{[['services','模型服务'],['tests','能力测试'],['routes','节点分工'],['defaults','流程偏好']].map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</nav><div className="settings-content">
 {tab==='services'&&<><div className="section-intro"><h3>连接服务，再分配给创作环节</h3><p>不同分组可分别添加服务，填写该分组的 Key 和模型。分组权限由中转站绑定的 Key 决定。</p><a className="text-link" href="https://apikey.fan/docs#ApiScripts" target="_blank" rel="noreferrer">查看 APIKEY.FAN 接入说明</a></div>
 {cfg.services.map((s,i)=><section className="service-card" key={s.id}><div className="row between"><h4>服务 {String(i+1).padStart(2,'0')}</h4><div className="row"><Tag tone={s.status==='tested'?'green':''}>{s.status==='tested'?'文本已验证':'文本未验证'}</Tag><button className="icon-button" title="删除服务" onClick={()=>setCfg(c=>({...c,services:c.services.filter(x=>x.id!==s.id),default_service:c.default_service===s.id?'':c.default_service}))}><Trash2 size={16}/></button></div></div>
 <Field label="服务名称 / 分组备注" value={s.name} onCommit={v=>change(s.id,{name:v})}/><Select label="接入预设" value={s.protocol} onChange={v=>change(s.id,{protocol:v})}>{presets.map(([id,label])=><option key={id} value={id}>{label}</option>)}</Select><p className="muted small-text">按服务商文档选择；厂商名称不等于接口协议。此选择不会改变 Key 所属分组。</p>
 <Field label="调用地址" value={s.base_url} onCommit={v=>change(s.id,{base_url:v})}/><Field label="API Key" type="password" value={s.key??''} placeholder={s.key_set?'已加密保存，留空保持不变':'粘贴该分组的 API Key'} onCommit={v=>change(s.id,{key:v||undefined})}/>
 <div className="row align-end"><div className="grow"><Field label="默认模型名称" value={s.model} placeholder="填写服务商提供的准确模型 ID" onCommit={v=>change(s.id,{model:v})}/></div><button disabled={!!busy} className="button secondary" onClick={()=>action('models',async()=>{await save();const r=await api('/services/'+s.id+'/models','POST');setModels(m=>({...m,[s.id]:r.models}));setNotice('已读取模型列表，也可手动填写。')})}>读取模型</button></div>
 {models[s.id]?.length>0&&<Select label="可用模型" value="" onChange={v=>change(s.id,{model:v})}><option value="">从列表选择…</option>{models[s.id].map(m=><option key={m}>{m}</option>)}</Select>}
 <details><summary>高级设置：协议、参数与价格</summary><Select label="接口协议" value={s.protocol} onChange={v=>change(s.id,{protocol:v})}><option value="chat">OpenAI Chat Completions</option><option value="responses">OpenAI Responses</option><option value="anthropic">Anthropic Messages</option></Select><div className="form-grid"><Field label="最大输出 Token" type="number" value={s.max_tokens} onCommit={v=>change(s.id,{max_tokens:Number(v)})}/><Field label="温度（可留空）" type="number" value={s.temperature??''} onCommit={v=>change(s.id,{temperature:v===''?null:Number(v)})}/><Field label="输入价格 / 百万 Token" type="number" value={s.input_price??''} onCommit={v=>change(s.id,{input_price:v===''?null:Number(v)})}/><Field label="输出价格 / 百万 Token" type="number" value={s.output_price??''} onCommit={v=>change(s.id,{output_price:v===''?null:Number(v)})}/><Field label="图片预估价格 / 张" type="number" value={s.image_price??''} onCommit={v=>change(s.id,{image_price:v===''?null:Number(v)})}/><Field label="原生搜索工具价格 / 次" type="number" value={s.search_price??''} onCommit={v=>change(s.id,{search_price:v===''?null:Number(v)})}/><Select label="计价货币" value={s.currency} onChange={v=>change(s.id,{currency:v})}><option value="CNY">人民币 CNY</option><option value="USD">美元 USD</option></Select></div><p className="muted">未知价格保持留空，不能填 0 代替未知。搜索工具费与模型 Token 分别记录。</p></details>
 <button disabled={!!busy} className="button secondary" onClick={()=>action('text',async()=>{await save();const r=await api('/services/'+s.id+'/test','POST');await reload();setNotice(r.message)})}><PlugZap size={15}/>测试文本连接</button></section>)}
 <button className="button secondary" onClick={add}><Plus size={16}/>添加模型服务</button>
 </>}
 {tab==='tests'&&<ModelTests cfg={cfg} busy={!!busy} onProtocol={protocol} onTest={(c,k)=>void test(c,k)}/>}
 {tab==='routes'&&<><div className="section-intro"><h3>逐节点分配模型</h3><p>检索规划默认继承素材分析服务；能力测试可独立验证每个已配置模型。</p></div><Select label="共享默认服务" value={cfg.default_service} onChange={v=>setCfg(c=>({...c,default_service:v,route_capabilities:{}}))}><option value="">请选择</option>{cfg.services.map(s=><option key={s.id} value={s.id}>{s.name} · {s.model||'未填写模型'}</option>)}</Select>{routes.map(r=><div className="route-row" key={r}><strong>{LABELS[r]}</strong><select aria-label={LABELS[r]+'服务'} value={cfg.routes[r]?.service_id||''} onChange={e=>setCfg(c=>({...c,route_capabilities:{},routes:{...c.routes,[r]:{model:c.routes[r]?.model||'',service_id:e.target.value}}}))}><option value="">{r==='research'?'继承素材分析服务':'使用默认服务'}</option>{cfg.services.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><Field label="模型覆盖" value={cfg.routes[r]?.model||''} placeholder="留空继承模型" onCommit={v=>setCfg(c=>({...c,route_capabilities:{},routes:{...c.routes,[r]:{service_id:c.routes[r]?.service_id||'',model:v}}}))}/></div>)}</>}
 {tab==='defaults'&&<><SearchPreferences cfg={cfg} onChange={search}/><div className="section-intro"><h3>按你的节奏创作</h3><p>用于新建文章，每篇仍可以独立调整。检索自动完成，节点确认习惯保持不变。</p></div><div className="row"><button className="button secondary" onClick={()=>setCfg(c=>({...c,default_auto:Object.fromEntries(Object.keys(c.default_auto).map(s=>[s,false]))}))}>全部手动</button><button className="button secondary" onClick={()=>setCfg(c=>({...c,default_auto:Object.fromEntries(Object.keys(c.default_auto).map(s=>[s,true]))}))}>全部自动</button></div>{Object.entries(cfg.default_auto).map(([s,v])=><div className="preference-row" key={s}><span>{LABELS[s]}</span><Toggle checked={v} onChange={v=>setCfg(c=>({...c,default_auto:{...c.default_auto,[s]:v}}))} label={v?'自动继续':'完成后等我确认'}/></div>)}</>}
 </div></div><div className="modal-footer"><span className="privacy"><ShieldCheck size={15}/>Key 使用 Windows 当前用户加密保存</span><div className="row">{busy&&<Busy/>}<button className="button primary" disabled={!!busy} onClick={()=>action('save',async()=>{await save();setNotice('设置已保存')})}><Check size={16}/>保存设置</button></div></div>{notice&&<div className="settings-notice" role="status">{notice}</div>}</Modal>
}
