import {useState} from 'react';
import {Plus,Trash2,PlugZap,ShieldCheck,Check} from 'lucide-react';
import {api} from './api';
import {SEARCH_PREFERENCES} from './SearchStrategy';
import SearchCheckPanel from './SearchCheckPanel';
import {type Settings as Config,type Service,LABELS} from './types';
import {Modal,Field,Select,Toggle,Busy,Tag} from './ui';

const presets=[['chat','OpenAI 兼容 · 通用文本'],['responses','OpenAI Responses · 文本与工具'],['anthropic','Claude · 原生 Messages']];
export default function Settings({initial,onClose,onSaved}:{initial:Config;onClose:()=>void;onSaved:(c:Config)=>void}){
 const [cfg,setCfg]=useState<Config>(structuredClone(initial));const [tab,setTab]=useState('services');const [busy,setBusy]=useState('');const [notice,setNotice]=useState('');const [picture,setPicture]=useState(initial.route_capabilities?.image?.image_url||'');const [models,setModels]=useState<Record<string,string[]>>({});
 const [configVersion,setConfigVersion]=useState(0);const [nativeResult,setNativeResult]=useState<any>(initial.route_capabilities?.search);
 const routes=['topic','sources','research','outline','write','review','revise','visual','image','layout_advice'];
 function change(id:string,patch:Partial<Service>){setCfg(c=>({...c,services:c.services.map(s=>s.id===id?{...s,...patch,status:'untested'}:s),route_capabilities:{}}))}
 function search(patch:Partial<Config['search']>){const nativeChanged=['native_service_id','native_model','native_protocol'].some(k=>k in patch);if(nativeChanged)setNativeResult(null);setCfg(c=>({...c,search:{...c.search,...patch},route_capabilities:nativeChanged?{...c.route_capabilities,search:{status:'untested'}}:c.route_capabilities}))}
 async function save(){const c=await api<Config>('/settings','PUT',cfg);setCfg(c);onSaved(c);setConfigVersion(v=>v+1);return c}
 async function action(name:string,fn:()=>Promise<void>){setBusy(name);setNotice('');try{await fn()}catch(e){setNotice(e instanceof Error?e.message:'操作未完成，请重试')}finally{setBusy('')}}
 async function reload(){const c=await api<Config>('/settings');setCfg(c);onSaved(c);setConfigVersion(v=>v+1)}
 function add(){const id=crypto.randomUUID();setCfg(c=>({...c,default_service:c.default_service||id,services:[...c.services,{id,name:'APIKEY.FAN',base_url:'https://api.apikey.fan',protocol:'chat',model:'',key_set:false,status:'untested',image_status:'untested',currency:'CNY',max_tokens:8000}]}))}
 const imageRoute=cfg.routes.image;const imageService=cfg.services.find(s=>s.id===(imageRoute?.service_id||cfg.default_service));const imageModel=imageRoute?.model||imageService?.model;
 const searchService=cfg.services.find(s=>s.id===(cfg.search.native_service_id||cfg.default_service));
 const state=(kind:string)=>kind==='search'&&(cfg.search.native_protocol==='inherit'&&searchService?.protocol==='chat')?'当前接入方式未验证':cfg.route_capabilities?.[kind]?.status==='tested'?'已验证':cfg.route_capabilities?.[kind]?.status==='failed'?'验证未通过':'尚未验证';
 return <Modal title="AI 服务与偏好" onClose={onClose} wide><div className="settings-shell"><nav className="settings-tabs">{[['services','模型服务'],['tests','能力测试'],['routes','节点分工'],['defaults','流程偏好']].map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</nav><div className="settings-content">
 {tab==='services'&&<><div className="section-intro"><h3>连接服务，再分配给创作环节</h3><p>不同分组可分别添加服务，填写该分组的 Key 和模型。分组权限由中转站绑定的 Key 决定。</p><a className="text-link" href="https://apikey.fan/docs#ApiScripts" target="_blank" rel="noreferrer">查看 APIKEY.FAN 接入说明</a></div>
 {cfg.services.map((s,i)=><section className="service-card" key={s.id}><div className="row between"><h4>服务 {String(i+1).padStart(2,'0')}</h4><div className="row"><Tag tone={s.status==='tested'?'green':''}>{s.status==='tested'?'文本已验证':'文本未验证'}</Tag><button className="icon-button" title="删除服务" onClick={()=>setCfg(c=>({...c,services:c.services.filter(x=>x.id!==s.id),default_service:c.default_service===s.id?'':c.default_service}))}><Trash2 size={16}/></button></div></div>
 <Field label="服务名称 / 分组备注" value={s.name} onCommit={v=>change(s.id,{name:v})}/><Select label="接入预设" value={s.protocol} onChange={v=>change(s.id,{protocol:v})}>{presets.map(([id,label])=><option key={id} value={id}>{label}</option>)}</Select><p className="muted small-text">按服务商文档选择；厂商名称不等于接口协议。此选择不会改变 Key 所属分组。</p>
 <Field label="调用地址" value={s.base_url} onCommit={v=>change(s.id,{base_url:v})}/><Field label="API Key" type="password" value={s.key??''} placeholder={s.key_set?'已加密保存，留空保持不变':'粘贴该分组的 API Key'} onCommit={v=>change(s.id,{key:v||undefined})}/>
 <div className="row align-end"><div className="grow"><Field label="默认模型名称" value={s.model} placeholder="填写服务商提供的准确模型 ID" onCommit={v=>change(s.id,{model:v})}/></div><button disabled={!!busy} className="button secondary" onClick={()=>action('models',async()=>{await save();const r=await api('/services/'+s.id+'/models','POST');setModels(m=>({...m,[s.id]:r.models}));setNotice('已读取模型列表，也可手动填写。')})}>读取模型</button></div>
 {models[s.id]?.length>0&&<Select label="可用模型" value="" onChange={v=>change(s.id,{model:v})}><option value="">从列表选择…</option>{models[s.id].map(m=><option key={m}>{m}</option>)}</Select>}
 <details><summary>高级设置：协议、参数与价格</summary><Select label="接口协议" value={s.protocol} onChange={v=>change(s.id,{protocol:v})}><option value="chat">OpenAI Chat Completions</option><option value="responses">OpenAI Responses</option><option value="anthropic">Anthropic Messages</option></Select><div className="form-grid"><Field label="最大输出 Token" type="number" value={s.max_tokens} onCommit={v=>change(s.id,{max_tokens:Number(v)})}/><Field label="温度（可留空）" type="number" value={s.temperature??''} onCommit={v=>change(s.id,{temperature:v===''?null:Number(v)})}/><Field label="输入价格 / 百万 Token" type="number" value={s.input_price??''} onCommit={v=>change(s.id,{input_price:v===''?null:Number(v)})}/><Field label="输出价格 / 百万 Token" type="number" value={s.output_price??''} onCommit={v=>change(s.id,{output_price:v===''?null:Number(v)})}/><Field label="图片预估价格 / 张" type="number" value={s.image_price??''} onCommit={v=>change(s.id,{image_price:v===''?null:Number(v)})}/><Field label="原生搜索工具价格 / 次" type="number" value={s.search_price??''} onCommit={v=>change(s.id,{search_price:v===''?null:Number(v)})}/><Select label="计价货币" value={s.currency} onChange={v=>change(s.id,{currency:v})}><option value="CNY">人民币 CNY</option><option value="USD">美元 USD</option></Select></div><p className="muted">未知价格保持留空，不能填 0 代替未知。搜索工具费与模型 Token 分别记录。</p></details>
 <button disabled={!!busy} className="button secondary" onClick={()=>action('text',async()=>{await save();const r=await api('/services/'+s.id+'/test','POST');await reload();setNotice(r.message)})}><PlugZap size={15}/>测试文本连接</button></section>)}
 <button className="button secondary" onClick={add}><Plus size={16}/>添加模型服务</button>
 </>}
 {tab==='tests'&&<><div className="section-intro"><h3>四种能力，分别验证</h3><p>测试会真实调用所选接口，可能产生费用；保存设置不会自动触发测试。</p></div>{cfg.services.map(s=><section className="service-card" key={s.id}><h4>文本 · {s.name}</h4><p className="muted">{s.model||'未填写模型'}</p><button className="button secondary" disabled={!!busy||!s.model} onClick={()=>action('text',async()=>{await save();const r=await api('/services/'+s.id+'/test','POST');await reload();setNotice(r.message)})}>测试文本连接</button></section>)}<section className="service-card capability-card"><div className="row between"><h3>图片能力测试</h3><Tag>{state('image')}</Tag></div><p>使用图片生成节点：<strong>{imageService?.name||'未选择服务'} · {imageModel||'未填写图片模型'}</strong></p><p className="muted">会实际生成 1 张图片。{imageService?.image_price==null?'费用未知，可能产生费用。':`预计 ${imageService.image_price} ${imageService.currency}，实际费用以中转站账单为准。`}</p><div className="row wrap"><button className="button primary" disabled={!!busy||!imageModel} onClick={()=>action('image',async()=>{await save();const r=await api('/services/'+imageService!.id+'/test-image','POST');setPicture(r.image_url);await reload();setNotice(r.message)})}>生成测试图片 · 1 张</button><button className="text-button" onClick={()=>setTab('routes')}>设置图片服务和模型</button></div>{picture&&state('image')==='已验证'&&<img className="connection-preview" src={picture} alt="实际生成的连接测试图片"/>}</section>
 <section className="service-card"><h3>联网搜索方式</h3><Select label="优先搜索方式" value={cfg.search.preference||'auto'} onChange={v=>search({preference:v})}>{Object.entries(SEARCH_PREFERENCES).map(([v,label])=><option key={v} value={v}>{label}{v==='auto'?'（默认）':''}</option>)}</Select><Toggle checked={cfg.search.allow_fallback!==false} onChange={v=>search({allow_fallback:v})} label="首选方式失败或资料不足时，允许自动切换"/><p className="muted">一次设置后自动执行。自动模式保留学术优先与可用渠道选择；指定方式时先尝试它，再补查论文。关闭切换后，不改用另外两种方式；浏览器内部仍可切换搜索引擎。</p><p className="muted">论文补查、原文读取及引用核对独立保留，共享已有次数与预算限额。当前首选方式未配置或无法使用时，会说明原因。</p>{cfg.search.preference==='native'&&<p className="notice">当前联网模型：{searchService?.name||'未配置'} · {cfg.search.native_model||searchService?.model||'未填写'} · {state('search')}。<button className="text-button" onClick={()=>document.getElementById('native-search-settings')?.scrollIntoView({behavior:'smooth',block:'start'})}>设置或验证联网模型</button></p>}{cfg.search.preference==='tavily'&&(!cfg.search.tavily_enabled||!cfg.search.key_set)&&<p className="notice amber">Tavily 尚未启用或未保存 Key，请在下方“搜索设置”中配置。{cfg.search.allow_fallback?'允许使用其他方式。':'自动切换已关闭，将提示你处理。'}</p>}{cfg.search.preference==='browser'&&!cfg.search.browser_enabled&&<p className="notice amber">浏览器检索已关闭，请在下方搜索设置中启用。</p>}</section><SearchCheckPanel save={save} disabled={!!busy} configVersion={configVersion}/><details className="service-card"><summary>搜索设置 · 渠道、自动检索与限额</summary><p>搜索顺序遵循上方选择；浏览器内部依次尝试 Google、Bing、百度、DuckDuckGo。学术补查由独立开关控制。</p><Toggle checked={cfg.search.enabled} onChange={v=>search({enabled:v})} label="创作时自动检索与核对来源"/><Toggle checked={cfg.search.academic_enabled} onChange={v=>search({academic_enabled:v})} label="自动跨库学术发现 · OpenAlex / Crossref"/><Toggle checked={cfg.search.arxiv_enabled} onChange={v=>search({arxiv_enabled:v})} label="AI 等领域补充 arXiv 预印本"/><Field label="OpenAlex 可选免费 Key" type="password" value={cfg.search.openalex_key??''} placeholder={cfg.search.openalex_key_set?'已加密保存':'留空使用可用的免费访问'} onCommit={v=>search({openalex_key:v||undefined})}/><p className="muted">跨学科发现不可用时使用 Crossref 补位；来源按 DOI、论文标识及题名合并，不把同一论文重复算作独立证据。</p> <div className="preference-row"><span>公开科研资料 · PubMed</span><Toggle checked={cfg.search.pubmed_enabled} onChange={v=>search({pubmed_enabled:v})} label="自动补充研究摘要"/></div><div className="preference-row"><span>本地浏览器 · Edge / Chrome</span><Toggle checked={cfg.search.browser_enabled} onChange={v=>search({browser_enabled:v})} label="允许后台搜索与网页读取"/></div><p className="muted">浏览器使用独立工作台环境；不会接管日常标签。个别网站受限时优先寻找替代来源。</p>
 <details><summary>检索限额与费用</summary><div className="form-grid"><Field label="每次任务最多搜索调用" type="number" value={cfg.search.max_calls} onCommit={v=>search({max_calls:Number(v)})}/><Field label="每次任务最多读取页面" type="number" value={cfg.search.max_pages} onCommit={v=>search({max_pages:Number(v)})}/><Field label="最多补查轮数" type="number" value={cfg.search.max_rounds} onCommit={v=>search({max_rounds:Number(v)})}/><Field label="本次任务搜索工具预算 / 元（可留空）" type="number" value={cfg.search.budget??''} onCommit={v=>search({budget:v===''?null:Number(v)})}/></div><p className="muted">预算仅约束搜索工具费，模型 Token 另计。填写金额后，价格未知或非人民币的付费渠道将跳过；留空仍受次数限制。未知结果的付费请求保留预算占用，不自动重复。</p></details>
 <details><summary>Tavily 可选后备渠道</summary><Toggle checked={cfg.search.tavily_enabled} onChange={v=>search({tavily_enabled:v})} label="启用 Tavily"/><Field label="Tavily 调用地址" value={cfg.search.base_url} onCommit={v=>search({base_url:v})}/><Field label="Tavily API Key" type="password" value={cfg.search.key??''} placeholder={cfg.search.key_set?'已加密保存':'可不填写'} onCommit={v=>search({key:v||undefined})}/><Field label="每次搜索工具价格 / 元" type="number" value={cfg.search.tavily_price??''} onCommit={v=>search({tavily_price:v===''?null:Number(v)})}/><button disabled={!!busy} className="button secondary" onClick={()=>action('tavily',async()=>{await save();const r=await api('/search/test','POST');setNotice(r.message)})}>测试 Tavily</button></details></details><section className="service-card" id="native-search-settings"><div className="row between"><h4>模型联网测试</h4><Tag>{state('search')}</Tag></div><Select label="搜索服务" value={cfg.search.native_service_id} onChange={v=>search({native_service_id:v})}><option value="">使用默认服务</option>{cfg.services.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</Select><Field label="搜索模型" value={cfg.search.native_model} placeholder="留空使用服务默认模型" onCommit={v=>search({native_model:v})}/><Select label="联网接入方式（不改变文本协议）" value={cfg.search.native_protocol||'inherit'} onChange={v=>search({native_protocol:v})}><option value="inherit">沿用原生文本协议（兼容旧设置）</option><option value="responses">OpenAI Responses · web_search</option><option value="anthropic">Anthropic Messages · web_search</option><option value="gemini">Gemini · Google Search</option></Select><p className="muted">只测试此处选择的一种方式。测试实际调用搜索工具，可能消耗余额。{searchService?.search_price==null?'工具费用未知。':`每次工具调用预计 ${searchService.search_price} ${searchService.currency}，另有模型用量。`}仅验证成功的接入参与模型联网检索；是否切换后备渠道遵循上方设置。</p><button disabled={!!busy||!searchService} className="button secondary" onClick={()=>action('native',async()=>{await save();try{const r=await api('/search/native/test','POST',{service_id:cfg.search.native_service_id,model:cfg.search.native_model,protocol:cfg.search.native_protocol});setNativeResult(r);setNotice(r.message)}finally{await reload()}})}>测试模型联网</button><p className="muted">未通过仅说明当前中转站接入方式未验证，不代表模型本身没有联网能力；工作台搜索可独立使用。Gemini 可能展开多个收费查询，费用以实际账单为准。</p>{nativeResult?.sources?.length>0&&<details><summary>查看本次模型联网记录与来源</summary><p>{(nativeResult.usage?.queries||nativeResult.queries||[]).join('；')}</p>{nativeResult.sources.map((r:any,i:number)=><p key={i}><a className="text-link research-url" href={r.url} target="_blank" rel="noreferrer">{r.title||r.url}</a></p>)}</details>}</section></>}
 {tab==='routes'&&<><div className="section-intro"><h3>逐节点分配模型</h3><p>检索规划默认继承素材分析服务；图片测试使用这里的图片生成配置。</p></div><Select label="共享默认服务" value={cfg.default_service} onChange={v=>setCfg(c=>({...c,default_service:v,route_capabilities:{}}))}><option value="">请选择</option>{cfg.services.map(s=><option key={s.id} value={s.id}>{s.name} · {s.model||'未填写模型'}</option>)}</Select>{routes.map(r=><div className="route-row" key={r}><strong>{LABELS[r]}</strong><select aria-label={LABELS[r]+'服务'} value={cfg.routes[r]?.service_id||''} onChange={e=>setCfg(c=>({...c,route_capabilities:{},routes:{...c.routes,[r]:{model:c.routes[r]?.model||'',service_id:e.target.value}}}))}><option value="">{r==='research'?'继承素材分析服务':'使用默认服务'}</option>{cfg.services.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><Field label="模型覆盖" value={cfg.routes[r]?.model||''} placeholder="留空继承模型" onCommit={v=>setCfg(c=>({...c,route_capabilities:{},routes:{...c.routes,[r]:{service_id:c.routes[r]?.service_id||'',model:v}}}))}/></div>)}</>}
 {tab==='defaults'&&<><div className="section-intro"><h3>按你的节奏创作</h3><p>用于新建文章，每篇仍可以独立调整。检索自动完成，节点确认习惯保持不变。</p></div><div className="row"><button className="button secondary" onClick={()=>setCfg(c=>({...c,default_auto:Object.fromEntries(Object.keys(c.default_auto).map(s=>[s,false]))}))}>全部手动</button><button className="button secondary" onClick={()=>setCfg(c=>({...c,default_auto:Object.fromEntries(Object.keys(c.default_auto).map(s=>[s,true]))}))}>全部自动</button></div>{Object.entries(cfg.default_auto).map(([s,v])=><div className="preference-row" key={s}><span>{LABELS[s]}</span><Toggle checked={v} onChange={v=>setCfg(c=>({...c,default_auto:{...c.default_auto,[s]:v}}))} label={v?'自动继续':'完成后等我确认'}/></div>)}</>}
 </div></div><div className="modal-footer"><span className="privacy"><ShieldCheck size={15}/>Key 使用 Windows 当前用户加密保存</span><div className="row">{busy&&<Busy/>}<button className="button primary" disabled={!!busy} onClick={()=>action('save',async()=>{await save();setNotice('设置已保存')})}><Check size={16}/>保存设置</button></div></div>{notice&&<div className="settings-notice" role="status">{notice}</div>}</Modal>
}
