export const STAGES=['topic','sources','outline','write','review','visual','layout'] as const;
export type Stage=typeof STAGES[number];
export const LABELS:Record<string,string>={research:'检索规划与资料整理',search:'搜索工具',topic:'选题',sources:'素材',outline:'大纲',write:'写作',review:'审核修改',visual:'配图',layout:'排版导出',revise:'修改选段',image:'生成图片',layout_advice:'排版建议'};
export const STATUS:Record<string,string>={idle:'未开始',done:'已完成',stale:'需要更新',needs_input:'待你确认'};
export interface Brief {column:string;domain:string;topic:string;audience:string;words:number;persona:string;tone:string;purpose:string;include:string;avoid:string;recent_days:number}
export interface Source {doi?:string;bibliography?:Record<string,any>;metadata_provenance?:any[];id:string;title:string;text:string;url:string;kind:string;status:string;selected:boolean;personal_material?:boolean;summary:string;use:string;pages:{page:number;text:string}[];provider?:string;published_date?:string;retrieved_at?:string;evidence_spans?:{quote:string;claim:string;boundary:string;location:string}[]}
export interface Outline {thesis:string;reader_question:string;takeaway:string;counterpoint:string;boundary:string;sections:{id:string;title:string;purpose:string;points:string[];claim_ids:string[]}[]}
export interface Article {id:string;title:string;revision:number;updated:string;brief:Brief;auto:Record<string,boolean>;stages:Record<string,string>;current_stage:string;topics:any[];sources:Source[];evidence:any;outline:Partial<Outline>;content:string;review:any;suggestions:any[];visual:{enabled:boolean;count:number;size:string;budget:number};image_plans:any[];images:any[];layout:{theme:string;font_size:number;line_height:number;paragraph_gap:number;author:string};layout_advice:string;research?:{stale?:boolean;strategy?:import('./SearchStrategy').Strategy;pending:boolean;summary:string;gaps:string[];conflicts:string[];calls:number;pages:number;rounds:number;log:{at:string;message:string;channel?:string;query?:string;reason?:string}[];blocked_urls:string[];job_id:string}}
export interface Service {id:string;name:string;base_url:string;protocol:string;model:string;key?:string;key_set:boolean;status:string;image_status:string;input_price?:number|null;output_price?:number|null;image_price?:number|null;currency:string;max_tokens:number;temperature?:number|null;search_price?:number|null}
export interface SearchConfig {preference:string;allow_fallback:boolean;native_protocol:string;academic_enabled:boolean;arxiv_enabled:boolean;openalex_key?:string;openalex_key_set:boolean;base_url:string;key?:string;key_set:boolean;enabled:boolean;native_service_id:string;native_model:string;browser_enabled:boolean;page_render_enabled:boolean;pubmed_enabled:boolean;tavily_enabled:boolean;tavily_price:number|null;max_calls:number;max_pages:number;max_rounds:number;budget:number|null}
export interface CapabilityResult {status:string;message?:string;at?:string;image_url?:string;sources?:{url:string;title:string}[];reply?:string;protocol?:string}
export interface ModelCard {service_id:string;model:string;name:string;roles:string[];search_protocol:string;capabilities:Record<string,CapabilityResult>}
export interface Settings {services:Service[];default_service:string;routes:Record<string,{service_id:string;model:string}>;search:SearchConfig;default_auto:Record<string,boolean>;model_connections?:{service_id:string;model:string;search_protocol:string}[];model_capabilities?:ModelCard[];route_capabilities?:Record<string,{status:string;model?:string;service?:string;image_url?:string}>}
export interface Meta {personas:{id:string;name:string;description:string;example:string}[];themes:{id:string;name:string;description:string;colors:Record<string,string>}[]}
export interface Job {id:string;article_id:string;stage:string;status:string;created:string;ended:string|null;message:string;partial:string;result:any;request:any}
export type Save=(changes:Partial<Article>,stage?:string)=>Promise<Article>;
