export const STAGES=['topic','sources','outline','write','review','visual','layout'] as const;
export type Stage=typeof STAGES[number];
export interface Source {notebook?:{read_characters?:number;total_characters?:number;notes:{category:string;note:string;quote:string;start:number;end:number}[];missing_categories:string[];pointers:{label:string;start:number}[]}}
export interface ResearchStats {provider_queries?:number}
export const LABELS:Record<string,string>={source_import:'导入资料',bound:'采用限定表述',research:'检索规划与资料整理',search:'搜索工具',topic:'选题',sources:'素材',outline:'大纲',write:'写作',review:'审核修改',visual:'配图',layout:'排版导出',revise:'修改选段',image:'生成图片',layout_advice:'阅读与结构建议'};
export const STATUS:Record<string,string>={idle:'未开始',done:'已完成',stale:'需要更新',needs_input:'待你确认'};
export interface Brief {column:string;domain:string;topic:string;audience:string;words:number;persona:string;tone:string;purpose:string;include:string;avoid:string;recent_days:number}
export interface Source {identity_status?:string;original_filename?:string;doi?:string;bibliography?:Record<string,any>;metadata_provenance?:any[];id:string;title:string;text:string;url:string;kind:string;status:string;selected:boolean;personal_material?:boolean;summary:string;use:string;pages:{page:number;text:string}[];provider?:string;published_date?:string;retrieved_at?:string;evidence_spans?:{quote:string;claim:string;boundary:string;location:string;source_type?:string;adoption_reason?:string;use_scope?:string;quality?:string}[]}
export interface Outline {thesis:string;reader_question:string;takeaway:string;counterpoint:string;boundary:string;sections:{id:string;title:string;purpose:string;points:string[];claim_ids:string[]}[]}
export type ApplicationState='pending'|'partial'|'applied'|'not_needed';
export interface AppliedEdit {target:string;section_id?:string;original:string;replacement:string;reason?:string}
export interface ResearchLimits {max_calls:number;max_pages:number;max_rounds:number}
export interface PageResult<T> {items:T[];total:number;page:number;page_size:number}
export interface ResearchIssue {application_state?:ApplicationState;priority?:"high"|"normal";application?:{job_id?:string;operation?:'bound'|'exclude';edits:AppliedEdit[];unapplied:AppliedEdit[];explanation:string};id:string;text:string;kind:"blocking"|"limitation";source_ids:string[];claim:string;status:string;resolution?:string;wording?:string}
export interface ResearchStats {version:number;existing_checked:number;search_requests:number;search_cache_hits:number;page_attempts:number;page_cache_hits:number;fulltext:number;abstracts:number;metadata_requests:number;metadata_cache_hits:number}
export interface Article {research_limits?:ResearchLimits;trashed_at?:string;creative_intent?:{selected?:any;direction_change?:string;feedback?:string[]};materials_state?:{state:string;message:string;action:string;ready:boolean;pending?:ResearchIssue[];required:ResearchIssue[];application_pending?:ResearchIssue[];boundaries:ResearchIssue[];handled:ResearchIssue[];new_source_ids:string[];delta?:{added_sources:number;resolved:number;remaining:number}|null;stop_reason:string};workflow?:Record<string,{allowed:boolean;reason:string;target:Stage}>;id:string;title:string;revision:number;updated:string;brief:Brief;auto:Record<string,boolean>;stages:Record<string,string>;current_stage:string;topics:any[];sources:Source[];evidence:any;outline:Partial<Outline>;content:string;review:any;suggestions:any[];visual:{enabled:boolean;count:number;size:string};image_plans:any[];images:any[];layout:{theme:string;font_size:number;line_height:number;paragraph_gap:number;author:string};layout_advice:string;research?:{coverage_sufficient?:boolean;coverage?:{question_id:string;question:string;required:boolean;status:string;reason:string;source_ids:string[]}[];limits?:{max_calls:number;max_pages:number;max_rounds:number};stage?:string;resume_job_id?:string;resume_stage?:string;issues?:ResearchIssue[];stats?:ResearchStats;stale?:boolean;strategy?:import('./SearchStrategy').Strategy;pending:boolean;summary:string;gaps:string[];conflicts:string[];calls:number;pages:number;rounds:number;log:{at:string;message:string;channel?:string;query?:string;reason?:string}[];blocked_urls:string[];job_id:string}}
export interface Service {id:string;name:string;base_url:string;protocol:string;model:string;key?:string;key_set:boolean;status:string;image_status:string;input_price?:number|null;output_price?:number|null;image_price?:number|null;currency:string;max_tokens:number;temperature?:number|null;search_price?:number|null}
export interface SearchConfig {preference:string;allow_fallback:boolean;native_protocol:string;academic_enabled:boolean;arxiv_enabled:boolean;openalex_key?:string;openalex_key_set:boolean;base_url:string;key?:string;key_set:boolean;enabled:boolean;native_service_id:string;native_model:string;browser_enabled:boolean;page_render_enabled:boolean;pubmed_enabled:boolean;tavily_enabled:boolean;tavily_price:number|null;max_calls:number;max_pages:number;max_rounds:number}
export interface CapabilityResult {status:string;message?:string;at?:string;image_url?:string;sources?:{url:string;title:string}[];reply?:string;protocol?:string}
export interface ModelCard {service_id:string;model:string;name:string;roles:string[];search_protocol:string;capabilities:Record<string,CapabilityResult>}
export interface Settings {services:Service[];default_service:string;routes:Record<string,{service_id:string;model:string}>;search:SearchConfig;default_auto:Record<string,boolean>;model_connections?:{service_id:string;model:string;search_protocol:string}[];model_capabilities?:ModelCard[];route_capabilities?:Record<string,{status:string;model?:string;service?:string;image_url?:string}>}
export interface Meta {personas:{id:string;name:string;description:string;example:string}[];themes:Theme[]}
export interface Job {resumed_from?:string;id:string;article_id:string;stage:string;status:string;created:string;ended:string|null;message:string;partial:string;result:any;request:any}
export type Save=(changes:Partial<Article>|((current:Article)=>Partial<Article>),stage?:string)=>Promise<Article>;

export interface Theme {id:string;name:string;description:string;colors:Record<string,string>;group:'editorial'|'classic';defaults:Pick<Article['layout'],'font_size'|'line_height'|'paragraph_gap'>}
