async (page) => {
  await page.getByRole('button',{name:'AI 服务与设置',exact:true}).click();
  await page.getByRole('button',{name:'添加模型服务',exact:true}).click();
  await page.getByLabel('服务名称',{exact:true}).fill('本地验收服务（模拟）');
  await page.getByLabel('调用地址',{exact:true}).fill('http://127.0.0.1:8878');
  await page.getByLabel('API Key',{exact:true}).fill('offline-test-key');
  await page.getByLabel('默认模型名称',{exact:true}).fill('qa-text-model');
  await page.getByRole('button',{name:'保存设置',exact:true}).click();
  await page.getByRole('status').filter({hasText:'设置已保存'}).waitFor();
  await page.getByRole('button',{name:'测试文本连接',exact:true}).click();
  await page.getByRole('status').filter({hasText:'文本调用成功'}).waitFor();
  await page.getByRole('button',{name:'节点分工',exact:true}).click();
  const route=page.locator('.route-row').filter({has:page.getByText('审核修改',{exact:true})});
  await route.getByLabel('模型覆盖',{exact:true}).fill('qa-review-model');
  const image=page.locator('.route-row').filter({has:page.getByText('生成图片',{exact:true})});
  await image.getByLabel('模型覆盖',{exact:true}).fill('qa-image-model');
  await page.getByRole('button',{name:'保存设置',exact:true}).click();
  await page.getByRole('button',{name:'模型服务',exact:true}).click();
  await page.getByText('高级参数与费用估算',{exact:true}).click();
  await page.getByLabel('图片预估价格 / 张',{exact:true}).fill('1');
  await page.getByRole('button',{name:'保存设置',exact:true}).click();
  await page.getByRole('button',{name:'关闭',exact:true}).click();
  await page.getByRole('button',{name:'开始一篇新文章',exact:true}).click();
  await page.getByLabel('想探索的领域',{exact:true}).fill('运动研究与证据解读');
  await page.getByRole('button',{name:'创建文章',exact:true}).click();
  await page.getByRole('heading',{name:'选题',exact:true}).waitFor();
  await page.getByRole('button',{name:'寻找选题灵感',exact:true}).click();
  await page.getByRole('button',{name:'就写这个'}).first().waitFor({timeout:15000});
  if(await page.locator('.topic-card').count()!==10)throw new Error('topic count mismatch');
  await page.screenshot({path:'output/playwright/topics.png',fullPage:false});
  await page.getByRole('button',{name:'就写这个'}).first().click();
  await page.getByRole('button',{name:'下一步 · 素材',exact:true}).click();
  await page.getByRole('button',{name:'粘贴文字',exact:true}).click();
  await page.getByLabel('素材名称',{exact:true}).fill('验收资料：研究解释边界');
  await page.getByLabel('素材正文',{exact:true}).fill('训练计划应结合个体条件与目标。研究结果的适用范围取决于研究人群、训练条件及观察指标，不能直接推广到所有人。这份文字是验证界面流程的材料，不是实际发表的研究。');
  await page.getByRole('button',{name:'添加素材',exact:true}).click();
  await page.locator('.source-card').waitFor();
  await page.getByRole('button',{name:'分析选中素材',exact:true}).click();
  await page.getByRole('heading',{name:'资料分析',exact:true}).waitFor({timeout:15000});
  await page.getByRole('button',{name:'下一步 · 大纲',exact:true}).click();
  await page.getByRole('button',{name:'生成文章大纲',exact:true}).click();
  await page.locator('.outline-card').first().waitFor({timeout:15000});
  await page.locator('.outline-card').first().getByLabel('章节标题',{exact:true}).fill('先问清楚：数字测量了什么');
  await page.getByRole('button',{name:'下一步 · 写作',exact:true}).click();
  await page.getByRole('button',{name:'生成初稿',exact:true}).click();
  await page.locator('.prose-editor').getByText('这意味着，这个结论对所有人都成立。',{exact:true}).waitFor({timeout:15000});
  return {url:page.url(),topics:10,draftGenerated:true};
}
