async (page) => {
  await page.getByRole('button',{name:/写作 已完成/}).click();
  await page.getByRole('textbox',{name:'已选中的内容',exact:true}).fill('但数字必须放回问题中，才能说明它的价值。');
  await page.getByRole('button',{name:'更简洁',exact:true}).click();
  await page.getByRole('button',{name:'生成修改建议',exact:true}).click();
  await page.getByRole('button',{name:'应用',exact:true}).waitFor({timeout:15000});
  await page.getByRole('button',{name:'应用',exact:true}).click();
  await page.locator('.prose-editor').getByText('先看清楚数字代表什么，再判断它是否回答了你的训练问题。',{exact:false}).waitFor();
  await page.locator('.prose-editor').click();
  await page.keyboard.press('Control+End');
  await page.keyboard.press('Enter');
  await page.keyboard.insertText('人工补充：这是一项离线界面验收。');
  await page.getByRole('button',{name:'下一步 · 审核修改',exact:true}).click();
  await page.getByRole('button',{name:'审核当前稿',exact:true}).click();
  await page.getByText('AI 审核通过',{exact:true}).waitFor({timeout:15000});
  const id=page.url().split('#')[1];
  const persisted=await page.evaluate(async id=>await (await fetch('/api/articles/'+id)).json(),id);
  if(!persisted.content.includes('人工补充'))throw new Error('manual edit lost');
  if(!persisted.content.includes('['+persisted.sources[0].id+']'))throw new Error('source reference lost after rich edit');
  await page.reload();
  await page.locator('.prose-editor').getByText('人工补充：这是一项离线界面验收。',{exact:true}).waitFor();
  await page.getByRole('button',{name:/配图 按需添加/}).click();
  await page.getByRole('switch',{name:'启用 AI 配图',exact:true}).click();
  await page.getByRole('button',{name:'生成配图方案',exact:true}).first().click();
  await page.getByRole('button',{name:'生成这一张',exact:true}).waitFor({timeout:15000});
  await page.getByRole('button',{name:'生成这一张',exact:true}).click();
  await page.locator('.image-card img').waitFor({timeout:15000});
  await page.getByRole('button',{name:'下一步 · 排版导出',exact:true}).click();
  await page.locator('iframe[title="公众号排版预览"]').waitFor();
  await page.getByLabel('排版主题',{exact:true}).selectOption('sspai');
  await page.getByLabel('署名',{exact:true}).fill('WeWrite 界面验收');
  await page.getByLabel('署名',{exact:true}).press('Tab');
  const download=page.waitForEvent('download');
  await page.getByRole('link',{name:'下载完整文章包',exact:true}).click();
  const result=await download;await result.saveAs('output/playwright/验收文章.zip');
  await page.context().grantPermissions(['clipboard-read','clipboard-write']);
  await page.getByRole('button',{name:'复制公众号排版',exact:true}).click();
  await page.getByRole('button',{name:'已复制',exact:true}).waitFor();
  const clipboard=await page.evaluate(async()=>await navigator.clipboard.readText());
  if(!clipboard.includes('人工补充'))throw new Error('clipboard lost content');
  await page.screenshot({path:'output/playwright/layout.png',fullPage:false});
  const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth);
  if(overflow)throw new Error('desktop horizontal overflow');
  return {revisionAccepted:true,manualEditRestored:true,citationsPreserved:true,imageGenerated:true,export:result.suggestedFilename(),clipboard:true,overflow:false};
}
