"""Explicit extension actions in the real UI; QA server mocks only network/model IO."""
import asyncio
import io
from PIL import Image
from playwright.async_api import expect


async def check(page,base,out):
    headers={'X-Studio-Request':'1'}
    a=await (await page.request.post(base+'/api/articles',headers=headers,data=dict(topic='扩展验收'))).json()
    original='这份模拟文章用于检查扩展功能。我们保留原稿，只创建独立平台版本，并核对每个工具返回的实际结果。'*8
    a=await (await page.request.patch(base+'/api/articles/'+a['id'],headers=headers,data=dict(revision=a['revision'],stage='write',changes=dict(content=original)))).json()
    blob=io.BytesIO();Image.new('RGB',(80,60),'green').save(blob,'PNG')
    response=await page.request.post(base+'/api/articles/'+a['id']+'/images/upload',headers=headers,multipart=dict(revision=str(a['revision']),role='cover',file=dict(name='fixture.png',mimeType='image/png',buffer=blob.getvalue())))
    assert response.ok
    await page.goto(base+'/#'+a['id'])
    await page.get_by_role('button',name='扩展',exact=True).click()
    dialog=page.get_by_role('dialog',name='创作扩展',exact=True)
    await dialog.get_by_role('button',name='自定义人格',exact=True).click()
    await dialog.get_by_text('高级：人格编号',exact=True).click()
    await dialog.get_by_label('自定义人格编号',exact=True).fill('user-fixture')
    await dialog.get_by_label('人格显示名称',exact=True).fill('验收读书人')
    await dialog.get_by_label('人格与语感',exact=True).fill('从具体问题展开，保留自然的声音。')
    await dialog.get_by_role('button',name='保存自定义人格',exact=True).click()
    await expect(dialog.get_by_role('button',name='编辑人格',exact=True)).to_be_visible()
    await dialog.get_by_role('button',name='学习排版',exact=True).click()
    await dialog.get_by_label('公众号排版参考链接',exact=True).fill('https://mp.weixin.qq.com/s/fixture-theme')
    await dialog.get_by_text('高级：主题编号',exact=True).click()
    await dialog.get_by_label('新主题编号',exact=True).fill('user-fixture-theme')
    await dialog.get_by_label('新主题显示名称',exact=True).fill('验收学习主题')
    await dialog.get_by_role('button',name='学习并保存主题',exact=True).click()
    await expect(dialog).to_contain_text('主题已加入排版下拉框')
    await dialog.get_by_role('button',name='多平台改写',exact=True).click()
    await dialog.get_by_role('button',name='生成独立平台稿',exact=True).click()
    await expect(dialog).to_contain_text('与源稿／其他平台最大相似度')
    await dialog.get_by_role('button',name='微信草稿箱',exact=True).click()
    await dialog.get_by_label('公众号 AppID',exact=True).fill('wx1234567890')
    await dialog.get_by_label('公众号 AppSecret',exact=True).fill('synthetic-wechat-secret')
    await dialog.get_by_role('button',name='保存公众号连接',exact=True).click()
    await expect(dialog).to_contain_text('已保存凭证')
    for kind,label in [('publish','将此文章推送到微信草稿箱'),('image_post','将采用图片推送为图片帖')]:
        await dialog.get_by_label('草稿类型',exact=True).select_option(kind)
        await dialog.get_by_role('button',name='查看推送预览',exact=True).click()
        await expect(dialog.get_by_role('button',name=label,exact=True)).to_be_enabled()
        await dialog.get_by_role('button',name=label,exact=True).click()
        await expect(dialog.get_by_role('button',name='查看推送预览',exact=True)).to_be_enabled()
        await expect(dialog).to_contain_text('offline-draft-')
    await dialog.get_by_role('button',name='读取微信草稿副本',exact=True).click()
    await expect(dialog).to_contain_text('微信模拟人工修改副本')
    await dialog.get_by_role('button',name='在线效果',exact=True).click()
    await dialog.get_by_label('微信统计文章编号（msgid）',exact=True).fill('123456_1')
    await dialog.get_by_role('button',name='关联当前文章',exact=True).click()
    await expect(dialog).to_contain_text('扩展验收 · 123456_1')
    await dialog.get_by_role('button',name='拉取并回填在线效果',exact=True).click()
    await expect(dialog).to_contain_text('阅读 120，分享 8，点赞 未知')
    await dialog.get_by_role('button',name='复盘已有数据（AI）',exact=True).click()
    await expect(dialog).to_contain_text('当前数据只能描述已有样本')
    for width in (1440,390):
        await page.set_viewport_size(dict(width=width,height=900))
        assert await page.evaluate('document.documentElement.scrollWidth<=innerWidth')
        assert await dialog.evaluate('(el)=>el.scrollWidth<=el.clientWidth')
        await page.screenshot(path=str(out/f'extensions-{width}.png'),full_page=True)
    await dialog.get_by_role('button',name='关闭',exact=True).click()
    await page.set_viewport_size(dict(width=1440,height=1000))
    await page.locator('.stage-nav').filter(has=page.locator('strong',has_text='排版导出')).click()
    await expect(page.get_by_label('排版主题',exact=True).locator('option[value="user-fixture-theme"]')).to_have_count(1)
    await page.get_by_label('排版主题',exact=True).select_option('user-fixture-theme')
    await expect(page.get_by_role('button',name='复制公众号排版',exact=True)).to_be_enabled()
    final=await (await page.request.get(base+'/api/articles/'+a['id'])).json()
    assert final['content']==original and any(x['action']=='publish' for x in final['extensions'])
